<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "ai_assistant" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'AI Assistant' => 'AI Asistan',
  'Topics' => 'Konular',
  'View topics' => 'Konuları görüntüle',
  'Topic' => 'Konu',
  'Subject' => 'Başlık',
  'Prompt' => 'İstem',
  'Create new topic' => 'Yeni konu oluştur',
  'The subject will appear when starting a new conversation.' => 'Başlık, yeni bir konuşma başlatırken görünecektir.',
  'This is the prompt that will always be sent as context for the conversation.' => 'Bu, konuşma için bağlam olarak her zaman gönderilecek olan istemdir.',
  'Chat GPT 3.5 turbo' => 'Chat GPT 3.5 turbo',
  'Chat GPT 4' => 'Chat GPT 4',
  'Text completion DaVinci 003' => 'Metin tamamlama DaVinci 003',
  'Enabled for customers' => 'Müşteriler için etkinleştirildi',
  'Customers use system OpenAI account' => 'Müşteriler sistem OpenAI hesabını kullanır',
  'Customers add own OpenAI account' => 'Müşteriler kendi OpenAI hesabını ekler',
  'Provide AI Assistant only for these customer groups' => 'AI Asistanı yalnızca bu müşteri grupları için sağla',
  'Secret key' => 'Gizli anahtar',
  'Model' => 'Model',
  'Max tokens' => 'Maksimum token',
  'Temperature' => 'Sıcaklık',
  'Frequency penalty' => 'Frekans cezası',
  'Presence penalty' => 'Varlık cezası',
  'Stop' => 'Dur',
  'The access secret key for OpenAI API' => 'OpenAI API için erişim gizli anahtarı',
  'Whether the customers can use this feature' => 'Müşterilerin bu özelliği kullanıp kullanamayacağı',
  'Whether customer can use the system OpenAI account if they don\'t have their own account' => 'Müşterilerin kendi hesapları yoksa sistem OpenAI hesabını kullanıp kullanamayacağı',
  'Whether customer can add their own OpenAI account' => 'Müşterilerin kendi OpenAI hesaplarını ekleyip ekleyemeyeceği',
  'The maximum number of tokens to generate in the completion. The token count of your prompt plus max_tokens cannot exceed the models context length. Most models have a context length of 2048 tokens (except for the newest models, which support 4096). We limited this to 2000 to make sure there are enough tokens for the response.' => 'Tamamlamada oluşturulacak maksimum token sayısı. İsteminizin token sayısı artı max_tokens, modellerin bağlam uzunluğunu aşamaz. Çoğu modelin 2048 token bağlam uzunluğu vardır (4096\'yı destekleyen en yeni modeller hariç). Yanıt için yeterli token olduğundan emin olmak için bunu 2000 ile sınırladık.',
  'What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. We generally recommend altering this or top_p but not both.' => 'Kullanılacak örnekleme sıcaklığı, 0 ile 2 arasında. 0.8 gibi yüksek değerler çıktıyı daha rastgele yaparken, 0.2 gibi düşük değerler daha odaklı ve belirleyici yapar. Genellikle bunu veya top_p\'yi değiştirmenizi öneririz, ancak ikisini birden değil.',
  'Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the models likelihood to repeat the same line verbatim. See more information about frequency and presence penalties.' => '-2.0 ile 2.0 arasında bir sayı. Pozitif değerler, şimdiye kadar metindeki mevcut frekanslarına göre yeni tokenleri cezalandırır ve modellerin aynı satırı aynen tekrarlama olasılığını azaltır. Frekans ve varlık cezaları hakkında daha fazla bilgi için bakın.',
  'Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the models likelihood to talk about new topics. See more information about frequency and presence penalties.' => '-2.0 ile 2.0 arasında bir sayı. Pozitif değerler, şimdiye kadar metinde görünüp görünmediklerine göre yeni tokenleri cezalandırır ve modellerin yeni konular hakkında konuşma olasılığını artırır. Frekans ve varlık cezaları hakkında daha fazla bilgi için bakın.',
  'Up to 4 sequences where the API will stop generating further tokens. The returned text will not contain the stop sequence.' => 'API\'nin daha fazla token oluşturmayı durduracağı en fazla 4 sıra. Döndürülen metin, durma sırasını içermeyecektir.',
  'Customers' => 'Müşteriler',
  'Here are some resources that might help you creating better prompts: {url}' => 'İşte daha iyi istemler oluşturmanıza yardımcı olabilecek bazı kaynaklar: {url}',
);
