<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "amazon_s3" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Amazon S3' => 'Amazon S3',
  'Common' => 'Genel',
  'Customers' => 'Müşteriler',
  'Uploaded email templates' => 'Yüklenen e-posta şablonları',
  'S3 access key' => 'S3 erişim anahtarı',
  'S3 access secret' => 'S3 erişim gizli anahtarı',
  'S3 region' => 'S3 bölgesi',
  'Enabled for customers' => 'Müşteriler için etkinleştirildi',
  'Customers use system S3 account' => 'Müşteriler sistem S3 hesabını kullanır',
  'Customers add own S3 account' => 'Müşteriler kendi S3 hesabını ekler',
  'Bucket name' => 'Bucket adı',
  'The access key for Amazon S3 service' => 'Amazon S3 hizmeti için erişim anahtarı',
  'The access secret for Amazon S3 service' => 'Amazon S3 hizmeti için erişim gizli anahtarı',
  'The region for Amazon S3 service' => 'Amazon S3 hizmeti için bölge',
  'Whether the customers can use this feature' => 'Müşterilerin bu özelliği kullanıp kullanamayacağı',
  'Whether customer can use the system S3 account if they don\'t have their own account' => 'Müşterilerin kendi hesapları yoksa sistem S3 hesabını kullanıp kullanamayacağı',
  'Whether customer can add their own S3 account' => 'Müşterilerin kendi S3 hesaplarını ekleyip ekleyemeyeceği',
  'Whether the assets from email templates should be sent to Amazon S3 service' => 'E-posta şablonlarındaki varlıkların Amazon S3 hizmetine gönderilip gönderilmeyeceği',
  'The bucket name where the assets will be sent' => 'Varlıkların gönderileceği bucket adı',
);
