<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "api" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Your IP address is not allowed to access this server.' => 'IP adresinizin bu sunucuya erişim izni bulunmamaktadır.',
  'Invalid API request params. Please refer to the documentation.' => 'Geçersiz API istek parametreleri. Lütfen dokümantasyona başvurun.',
  'Service Unavailable.' => 'Servis Kullanılamıyor.',
  'The subscribers list does not exist.' => 'Aboneler listesi mevcut değil.',
  'The subscribers list does not have any custom field defined.' => 'Aboneler listesinde tanımlanmış özel alan bulunmamaktadır.',
  'The subscriber does not exist in this list.' => 'Bu listede böyle bir abone bulunmamaktadır.',
  'Only POST requests allowed for this endpoint.' => 'Bu uç nokta sadece POST isteklerine izin vermektedir.',
  'Please provide the subscriber email address.' => 'Lütfen abone e-posta adresini belirtin.',
  'Please provide a valid email address.' => 'Lütfen geçerli bir e-posta adresi belirtin.',
  'The subscriber already exists in this list.' => 'Bu abone zaten listede mevcut.',
  'This email address is blacklisted.' => 'Bu e-posta adresi kara listeye alınmış.',
  'The field {field} is required by the list but it has not been provided!' => '{field} alanı liste için gerekli ancak sağlanmamış!',
  'Unable to save the subscriber!' => 'Abone kaydedilemedi!',
  'Please provide the subscribers list.' => 'Lütfen aboneler listesini belirtin.',
  'Only PUT requests allowed for this endpoint.' => 'Bu uç nokta sadece PUT isteklerine izin vermektedir.',
  'Another subscriber with this email address already exists in this list.' => 'Bu e-posta adresine sahip başka bir abone zaten listede mevcut.',
  'Only DELETE requests allowed for this endpoint.' => 'Bu uç nokta sadece DELETE isteklerine izin vermektedir.',
  'The template does not exist.' => 'Şablon mevcut değil.',
  'It does not seem that you have selected an archive.' => 'Bir arşiv seçmemiş görünüyorsunuz.',
  'Your archive does not seem to be a valid zip file.' => 'Arşiviniz geçerli bir zip dosyası gibi görünmüyor.',
  'Cannot write archive in the temporary location.' => 'Arşiv geçici konuma yazılamıyor.',
  'The list does not exist.' => 'Liste mevcut değil.',
  'You have reached the maximum number of allowed lists.' => 'İzin verilen maksimum liste sayısına ulaştınız.',
  'Unable to copy the list.' => 'Liste kopyalanamıyor.',
  'The campaign does not exist.' => 'Kampanya mevcut değil.',
  'The subscriber does not exist.' => 'Abone mevcut değil.',
  'The url hash does not exist.' => 'URL hash değeri mevcut değil.',
  'You have reached the maximum number of allowed campaigns.' => 'İzin verilen maksimum kampanya sayısına ulaştınız.',
  'Please provide a list for this campaign.' => 'Lütfen bu kampanya için bir liste belirtin.',
  'Provided list does not exist.' => 'Belirtilen liste mevcut değil.',
  'Provided list segment does not exist.' => 'Belirtilen liste segmenti mevcut değil.',
  'Provided template does not exist.' => 'Belirtilen şablon mevcut değil.',
  'Please provide a template for your campaign.' => 'Lütfen kampanyanız için bir şablon belirtin.',
  'Unable to copy the campaign.' => 'Kampanya kopyalanamıyor.',
  'The campaign does not allow marking it as sent!' => 'Kampanyanın gönderildi olarak işaretlenmesine izin verilmiyor!',
  'This campaign cannot be removed now.' => 'Bu kampanya şu anda kaldırılamaz.',
  'The email does not exist.' => 'E-posta mevcut değil.',
  'The campaign does not exist!' => 'Kampanya mevcut değil!',
  'The subscriber does not exist!' => 'Abone mevcut değil!',
  'This subscriber has already been marked as bounced!' => 'Bu abone zaten geri dönmüş olarak işaretlenmiş!',
  'Invalid bounce type!' => 'Geçersiz geri dönüş tipi!',
  'Customer creation is disabled.' => 'Müşteri oluşturma devre dışı.',
  'Unable to find the specified country, please double check the spelling!' => 'Belirtilen ülke bulunamıyor, lütfen yazımı tekrar kontrol edin!',
  'Unable to find the specified zone, please double check the spelling!' => 'Belirtilen bölge bulunamıyor, lütfen yazımı tekrar kontrol edin!',
);
