<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "app_monitor" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'CLI Monitor' => 'CLI İzleyici',
  'App Monitor' => 'Uygulama İzleyici',
  'Monitor Server IP' => 'İzleyici Sunucu IP',
  'Monitor Server port' => 'İzleyici Sunucu portu',
  'Monitor Server password' => 'İzleyici Sunucu şifresi',
  'The IP address of the Monitor Server' => 'İzleyici Sunucunun IP adresi',
  'The port of the Monitor Server' => 'İzleyici Sunucunun portu',
  'The password for the Monitor Server' => 'İzleyici Sunucunun şifresi',
);
