<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "articles" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View article categories' => 'Makale kategorilerini görüntüle',
  'Articles' => 'Makaleler',
  'Categories' => 'Kategoriler',
  'Create new article category' => 'Yeni makale kategorisi oluştur',
  'Update article category' => 'Makale kategorisini güncelle',
  'View zones' => 'Bölgeleri görüntüle',
  'View countries' => 'Ülkeleri görüntüle',
  'View articles' => 'Makaleleri görüntüle',
  'Create new article' => 'Yeni makale oluştur',
  'Update article' => 'Makaleyi güncelle',
  'Category' => 'Kategori',
  'Parent' => 'Üst kategori',
  'Name' => 'İsim',
  'Slug' => 'SEO URL',
  'Description' => 'Açıklama',
  'My category name' => 'Kategori adım',
  'my-category-name' => 'kategori-adim',
  'Article' => 'Makale',
  'Title' => 'Başlık',
  'Content' => 'İçerik',
  'Published' => 'Yayınlandı',
  'Unpublished' => 'Yayınlanmadı',
  'My article title' => 'Makale başlığım',
  'my-article-title' => 'makale-basligim',
  'Related articles' => 'İlgili makaleler',
  'Helpful articles' => 'Faydalı makaleler',
  'This article is unpublished, only site admins can see it!' => 'Bu makale yayınlanmadı, sadece site yöneticileri görebilir!',
  'All articles filled in under this category' => 'Bu kategori altındaki tüm makaleler',
  'We\'re sorry, but this category doesn\'t have any published article yet!' => 'Üzgünüz, bu kategoride henüz yayınlanmış makale bulunmuyor!',
  'List of helpful articles' => 'Faydalı makaleler listesi',
  'We\'re sorry, but for now there is no published article!' => 'Üzgünüz, şu an yayınlanmış makale bulunmuyor!',
);
