<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "campaign_activity_map" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Show opens map' => 'Açılış haritasını göster',
  'Show clicks map' => 'Tıklama haritasını göster',
  'Opens at once' => 'Tek seferde açılışlar',
  'Clicks at once' => 'Tek seferde tıklamalar',
  'Show unsubscribes map' => 'Abonelikten çıkma haritasını göster',
  'Unsubscribes at once' => 'Tek seferde abonelikten çıkmalar',
  'Google maps API key' => 'Google Haritalar API anahtarı',
  'Whether to show a map with location opens in campaign overview' => 'Kampanya genel bakışında konum açılışlarını gösteren bir harita gösterilip gösterilmeyeceği',
  'Whether to show a map with location clicks in campaign overview' => 'Kampanya genel bakışında konum tıklamalarını gösteren bir harita gösterilip gösterilmeyeceği',
  'How many open records to load at once per ajax call? More records means more memory usage' => 'Ajax çağrısı başına bir kerede kaç açılış kaydı yüklensin? Daha fazla kayıt daha fazla bellek kullanımı demektir',
  'How many click records to load at once per ajax call? More records means more memory usage' => 'Ajax çağrısı başına bir kerede kaç tıklama kaydı yüklensin? Daha fazla kayıt daha fazla bellek kullanımı demektir',
  'Whether to show a map with location from where subscribers unsubscribed in campaign overview' => 'Kampanya genel bakışında abonelerin abonelikten çıktığı konumları gösteren bir harita gösterilip gösterilmeyeceği',
  'How many unsubscribe records to load at once per ajax call? More records means more memory usage' => 'Ajax çağrısı başına bir kerede kaç abonelikten çıkma kaydı yüklensin? Daha fazla kayıt daha fazla bellek kullanımı demektir',
  'Your google maps API key. It is optional but needed if you go over the free quota assigned by Google' => 'Google Haritalar API anahtarınız. İsteğe bağlıdır ancak Google tarafından atanan ücretsiz kotayı aşarsanız gereklidir',
  'Campaign activity map' => 'Kampanya aktivite haritası',
  'Decide whether to show various maps in the campaign overview area.' => 'Kampanya genel bakış alanında çeşitli haritaların gösterilip gösterilmeyeceğine karar verin.',
);
