<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "ckeditor" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Enable filemanager for users' => 'Kullanıcılar için dosya yöneticisini etkinleştir',
  'Enable filemanager for customers' => 'Müşteriler için dosya yöneticisini etkinleştir',
  'Default toolbar' => 'Varsayılan araç çubuğu',
  'Filemanager theme' => 'Dosya yöneticisi teması',
  'Whether to enable the filemanager for users' => 'Kullanıcılar için dosya yöneticisi etkinleştirilsin mi',
  'Whether to enable the filemanager for customers' => 'Müşteriler için dosya yöneticisi etkinleştirilsin mi',
  'Default toolbar for all editor instances' => 'Tüm editör örnekleri için varsayılan araç çubuğu',
  'The file manager theme' => 'Dosya yöneticisi teması',
  'CKeditor options' => 'CKeditor seçenekleri',
  'Filemanager' => 'Dosya yöneticisi',
  'File manager' => 'Dosya yöneticisi',
  'Enable the editor' => 'Editörü etkinleştir',
  'File manager theme' => 'Dosya yöneticisi teması',
  'Whether to enable the editor' => 'Editör etkinleştirilsin mi',
);
