<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "common_email_templates" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View email templates' => 'E-posta şablonlarını görüntüle',
  'Common email templates' => 'Genel e-posta şablonları',
  'Create new template' => 'Yeni şablon oluştur',
  'Update template' => 'Şablonu güncelle',
  'This will delete the core email templates and will reinstall them based on the common template. Are you sure you want to continue?' => 'Bu işlem, temel e-posta şablonlarını silecek ve genel şablona göre yeniden yükleyecektir. Devam etmek istediğinizden emin misiniz?',
  'Reinstall core templates' => 'Temel şablonları yeniden yükle',
  'Available tags' => 'Kullanılabilir etiketler',
  'Tag' => 'Etiket',
  'Description' => 'Açıklama',
  'Template' => 'Şablon',
  'Name' => 'İsim',
  'Slug' => 'Kısa ad',
  'Subject' => 'Konu',
  'Content' => 'İçerik',
  'The name of the template, used internally mostly' => 'Şablonun adı, çoğunlukla dahili olarak kullanılır',
  'The subject which will be used for this email' => 'Bu e-posta için kullanılacak konu',
  'The email content' => 'E-posta içeriği',
  'Shows the current date' => 'Mevcut tarihi gösterir',
  'Shows the current year' => 'Mevcut yılı gösterir',
  'Shows the current month' => 'Mevcut ayı gösterir',
  'Shows the current day' => 'Mevcut günü gösterir',
  'Shows the site name' => 'Site adını gösterir',
);
