<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "company_types" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Company types' => 'Şirket Türleri',
  'Create new company type' => 'Yeni Şirket Türü Oluştur',
  'Update company type' => 'Şirket Türünü Güncelle',
  'Type' => 'Tür',
  'Name' => 'İsim',
);
