<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "console" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'ID' => 'ID',
  'Command' => 'Komut',
  'Action' => 'İşlem',
  'Params' => 'Parametreler',
  'Start time' => 'Başlangıç zamanı',
  'End time' => 'Bitiş zamanı',
  'Start memory' => 'Başlangıç belleği',
  'End memory' => 'Bitiş belleği',
  'Duration' => 'Süre',
  'Memory usage' => 'Bellek kullanımı',
  'seconds' => 'saniye',
);
