<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "cookie_consent" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Cookie consent' => 'Çerez izni',
  'Bottom' => 'Alt',
  'Bottom left' => 'Sol alt',
  'Bottom right' => 'Sağ alt',
  'Top' => 'Üst',
  'Top left' => 'Sol üst',
  'Top right' => 'Sağ üst',
  'Message' => 'Mesaj',
  'Position' => 'Konum',
  'Theme' => 'Tema',
  'Banner background color' => 'Banner arka plan rengi',
  'Button color' => 'Buton rengi',
  'This website uses cookies to improve your experience.' => 'Bu web sitesi, deneyiminizi iyileştirmek için çerezleri kullanmaktadır.',
  'The message that will appear on your cookie consent banner' => 'Çerez izin banner'ınızda görünecek mesaj',
  'Where the cookie consent banner will appear' => 'Çerez izin banner'ının görüneceği konum',
  'The theme of the cookie consent banner' => 'Çerez izin banner'ının teması',
  'Select background color' => 'Arka plan rengini seçin',
  'Reset background color' => 'Arka plan rengini sıfırla',
  'Select button color' => 'Buton rengini seçin',
  'Reset button color' => 'Buton rengini sıfırla',
);
