<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "countries" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View countries' => 'Ülkeleri Görüntüle',
  'Countries' => 'Ülkeler',
  'Create new country' => 'Yeni ülke oluştur',
  'Update country' => 'Ülkeyi güncelle',
  'Confirm country removal' => 'Ülke silme işlemini onayla',
  'Please note that removing this country will also remove every record that depends on it, such as zones, taxes, customer companies, etc!' => 'Lütfen dikkat: Bu ülkeyi silmek, bölgeler, vergiler, müşteri şirketleri vb. gibi buna bağlı tüm kayıtları da silecektir!',
  'Are you still sure you want to remove this country? There is no coming back after you do it!' => 'Bu ülkeyi silmek istediğinizden hala emin misiniz? Bu işlemi yaptıktan sonra geri dönüş olmayacak!',
  'Country' => 'Ülke',
  'Name' => 'İsim',
  'Code' => 'Kod',
);
