<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "cronjobs" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View cron jobs list' => 'Zamanlanmış görevler listesini görüntüle',
  'Cron jobs list' => 'Zamanlanmış görevler listesi',
  'View cron jobs history' => 'Zamanlanmış görevler geçmişini görüntüle',
  'Cron jobs history' => 'Zamanlanmış görevler geçmişi',
  'Showing various info about all the cron jobs that run for the application. We keep latest 10 records in the history for each cron job that runs.' => 'Uygulama için çalışan tüm zamanlanmış görevler hakkında çeşitli bilgiler gösteriliyor. Her çalışan zamanlanmış görev için geçmişte en son 10 kaydı tutuyoruz.',
  'Application cron jobs' => 'Uygulama zamanlanmış görevleri',
  'Description' => 'Açıklama',
  'Cronjob' => 'Zamanlanmış görev',
  'Please note that all the cron jobs below must be added on your server in order for the application to work properly.' => 'Lütfen uygulamanın düzgün çalışması için aşağıdaki tüm zamanlanmış görevlerin sunucunuza eklenmesi gerektiğini unutmayın.',
  'Please consult your web hosting knowledge base in order to understand how these cron jobs must be added on your server.' => 'Bu zamanlanmış görevlerin sunucunuza nasıl eklenmesi gerektiğini anlamak için lütfen web barındırma bilgi tabanınıza başvurun.',
);
