<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "cron_jobs" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Campaigns sender, runs each minute.' => 'Kampanya gönderici, her dakika çalışır.',
  'Queue handler, runs each minute.' => 'Kuyruk işleyici, her dakika çalışır.',
  'Transactional email sender, runs once at 2 minutes.' => 'İşlem e-posta gönderici, 2 dakikada bir çalışır.',
  'Bounce handler, runs once at 10 minutes.' => 'Geri dönüş işleyici, 10 dakikada bir çalışır.',
  'Feedback loop handler, runs once at 20 minutes.' => 'Geri bildirim döngüsü işleyici, 20 dakikada bir çalışır.',
  'Delivery/Bounce processor, runs once at 3 minutes.' => 'Teslim/Geri dönüş işlemcisi, 3 dakikada bir çalışır.',
  'Various tasks, runs each hour.' => 'Çeşitli görevler, her saat çalışır.',
  'Daily cleaner, runs once a day.' => 'Günlük temizleyici, günde bir kez çalışır.',
);
