<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "currencies" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View currencies' => 'Para birimlerini görüntüle',
  'Currencies' => 'Para birimleri',
  'Create new currency' => 'Yeni para birimi oluştur',
  'Update currency' => 'Para birimini güncelle',
  'Currency' => 'Para birimi',
  'Name' => 'İsim',
  'Code' => 'Kod',
  'Value' => 'Değer',
  'Is default' => 'Varsayılan mı',
  'Unrecognized currecy code!' => 'Tanınmayan para birimi kodu!',
);
