<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "custom_subscriber_attachment" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Custom subscriber attachment' => 'Özel abone eki',
  'Common' => 'Genel',
  'You have to set the absolute path to the storage folder where you will upload attachments. By default it is: {path}' => 'Ekleri yükleyeceğiniz depolama klasörü için mutlak yolu ayarlamanız gerekiyor. Varsayılan olarak: {path}',
  'After you set the storage folder, inside it, you can upload your subscriber specific attachments but make sure you create subfolders and you upload the attachments in these subfolders.' => 'Depolama klasörünü ayarladıktan sonra, içine aboneye özel eklerinizi yükleyebilirsiniz ancak alt klasörler oluşturduğunuzdan ve ekleri bu alt klasörlere yüklediğinizden emin olun.',
  'For example, you can have following structure:' => 'Örneğin, aşağıdaki yapıyı kullanabilirsiniz:',
  'Then in the campaign setup step, you will be able to select the "{folder}" folder as the folder from where the attachments will be loaded. Also, you will be able to select which custom field represents the file name.' => 'Daha sonra kampanya kurulum adımında, eklerin yükleneceği klasör olarak "{folder}" klasörünü seçebileceksiniz. Ayrıca, hangi özel alanın dosya adını temsil edeceğini de seçebileceksiniz.',
  'Storage folder' => 'Depolama klasörü',
  'The storage folder where the attachment folders will be created' => 'Ek klasörlerinin oluşturulacağı depolama klasörü',
);
