<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('Doğrudan komut dosyası erişimine izin verilmiyor');
}

/**
 * "customers" kategorisi için çeviri dosyası.
 *
 * Bu çeviri, Çeviri eklentisi tarafından otomatik olarak oluşturulur.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Please confirm your account!' => 'Lütfen hesabınızı onaylayın!',
  'New customer registration!' => 'Yeni müşteri kaydı!',
  'Subject' => 'Konu',
  'Message' => 'Mesaj',
  'Groups' => 'Gruplar',
  'Batch size' => 'Toplu işlem boyutu',
  'Unable to create the storage directory {dir}' => 'Depolama dizini {dir} oluşturulamıyor',
  'Unable to write in the storage directory {dir}' => 'Depolama dizinine {dir} yazılamıyor',
  '{group} ({count} customers)' => '{group} ({count} müşteri)',
  'View groups' => 'Grupları görüntüle',
  'Customers' => 'Müşteriler',
  'Create new group' => 'Yeni grup oluştur',
  'Create new customer group' => 'Yeni müşteri grubu oluştur',
  'Update group' => 'Grubu güncelle',
  'Update customer group' => 'Müşteri grubunu güncelle',
  'The sending quota has been successfully reseted!' => 'Gönderme kotası başarıyla sıfırlandı!',
  'Mass emails' => 'Toplu e-postalar',
  'Unable to load the message from written source!' => 'Mesaj yazılı kaynaktan yüklenemiyor!',
  'All emails were queued successfully!' => 'Tüm e-postalar başarıyla sıraya alındı!',
  'Please wait, queueing messages...' => 'Lütfen bekleyin, mesajlar sıraya alınıyor...',
  'Account' => 'Hesap',
  '2FA' => '2 Faktörlü Kimlik Doğrulama',
  'The 2FA code you have provided is not valid!' => 'Sağladığınız 2 Faktörlü Kimlik Doğrulama kodu geçerli değil!',
  'Password reset request!' => 'Şifre sıfırlama isteği!',
  'View login logs' => 'Giriş kayıtlarını görüntüle',
  'Login logs' => 'Giriş kayıtları',
  'View customers' => 'Müşterileri görüntüle',
  'Create new user' => 'Yeni kullanıcı oluştur', // Often 'user' and 'customer' are interchangeable in backend context. Keep consistent? Using 'kullanıcı' here.
  'Create new customer' => 'Yeni müşteri oluştur',
  'Update customer' => 'Müşteriyi güncelle',
  'The request has been registered!' => 'İstek kaydedildi!',
  'Your account has been approved!' => 'Hesabınız onaylandı!',
  'A notification email has been sent for this customer!' => 'Bu müşteri için bir bildirim e-postası gönderildi!',
  'Your account details!' => 'Hesap detaylarınız!',
  'The account details have been sent to the customer email address!' => 'Hesap detayları müşteri e-posta adresine gönderildi!',
  'Use any authenticator app such as Google Authenticator to scan the QR code below.' => 'Aşağıdaki QR kodunu taramak için Google Authenticator gibi herhangi bir kimlik doğrulama uygulamasını kullanın.',
  'You will then use the authenticator app to generate the code to login in the app.' => 'Daha sonra uygulamaya giriş yapmak için kodu oluşturmak üzere kimlik doğrulama uygulamasını kullanacaksınız.',
  'Manage groups' => 'Grupları yönet',
  'Are you sure you want to reset the sending quota for this customer?' => 'Bu müşteri için gönderme kotasını sıfırlamak istediğinizden emin misiniz?',
  'Manage customers' => 'Müşterileri yönet',
  'Are you sure you want to reset the sending quota for this group?' => 'Bu grup için gönderme kotasını sıfırlamak istediğinizden emin misiniz?',
  'Send message' => 'Mesaj gönder',
  'Following tags are available for message but also for subject: {tags}' => 'Aşağıdaki etiketler mesaj ve konu için kullanılabilir: {tags}',
  'If no group is selected, all customers will receive the email message.' => 'Grup seçilmezse, tüm müşteriler e-posta mesajını alacaktır.',
  'From a total of {total} customers, so far {processed} have been processed. {percentage} completed.' => 'Toplam {total} müşteriden şimdiye kadar {processed} işlendi. {percentage} tamamlandı.',
  'Messages' => 'Mesajlar',
  'Company' => 'Şirket',
  'Customer' => 'Müşteri',
  'Type/Industry' => 'Tür/Sektör',
  'Country' => 'Ülke',
  'Zone' => 'Bölge',
  'Name' => 'Ad',
  'Website' => 'Web sitesi',
  'Address' => 'Adres',
  'Address 2' => 'Adres 2',
  'Zone name' => 'Bölge adı',
  'City' => 'Şehir',
  'Zip code' => 'Posta kodu',
  'Phone' => 'Telefon',
  'Fax' => 'Faks',
  'VAT Number' => 'KDV Numarası',
  'Your company public display name' => 'Şirketinizin herkese açık görünen adı',
  'Please enter your website address url, starting with http:// or https://' => 'Lütfen http:// veya https:// ile başlayan web sitesi adresinizi girin',
  'Please select your company country zone. If none applicable, then please fill the zone name field instead.' => 'Lütfen şirketinizin ülke bölgesini seçin. Hiçbiri uygun değilse, bunun yerine bölge adı alanını doldurun.',
  'Please fill this field unless you have no option to select from the zone drop down.' => 'Bölge açılır menüsünden seçeneğiniz yoksa lütfen bu alanı doldurun.',
  'No check will be done against your city name, please be accurate!' => 'Şehir adınız kontrol edilmeyecektir, lütfen doğru bilgi girin!',
  'No check will be done against your zip code, please be accurate!' => 'Posta kodunuz kontrol edilmeyecektir, lütfen doğru bilgi girin!',
  'Option' => 'Seçenek',
  'Code' => 'Kod',
  'Is serialized' => 'Serileştirilmiş mi',
  'Value' => 'Değer',
  'Customer group(s) visibility' => 'Müşteri grubu/grupları görünürlüğü',
  'If no group is selected, all customers will see this plan. If one or more groups are selected, then just customers within these groups will see the plan.' => 'Grup seçilmezse, tüm müşteriler bu planı görecektir. Bir veya daha fazla grup seçilirse, yalnızca bu gruplardaki müşteriler planı görecektir.',
  'Request' => 'İstek',
  'Reset key' => 'Anahtarı sıfırla',
  'Ip address' => 'IP adresi',
  'Email' => 'E-posta',
  'Group' => 'Grup',
  'Is default' => 'Varsayılan mı',
  'Customers count' => 'Müşteri sayısı',
  'Mark' => 'İşaretle',
  'Cannot move the logo into the correct storage folder!' => 'Logo doğru depolama klasörüne taşınamıyor!',
  'ID' => 'Kimlik',
  'Unique ID' => 'Benzersiz Kimlik',
  'Language' => 'Dil',
  'First name' => 'Ad',
  'Last name' => 'Soyad',
  'Password' => 'Şifre',
  'Timezone' => 'Saat dilimi',
  'Avatar' => 'Avatar',
  'New avatar' => 'Yeni avatar',
  'Removable' => 'Kaldırılabilir',
  'Confirm email' => 'E-postayı onayla',
  'Confirm password' => 'Şifreyi onayla',
  'Terms and conditions' => 'Şartlar ve koşullar',
  'Sending quota usage' => 'Gönderme kotası kullanımı',
  'Send details via email' => 'Detayları e-posta ile gönder',
  'Birth date' => 'Doğum tarihi',
  'Inactivate at' => 'Pasifleştirme tarihi',
  '2FA enabled' => '2FA etkin',
  'Please make sure you scan the QR code in your authenticator application before enabling this feature, otherwise you will be locked out from your account' => 'Lütfen bu özelliği etkinleştirmeden önce QR kodunu kimlik doğrulama uygulamanızda taradığınızdan emin olun, aksi takdirde hesabınızdan kilitlenirsiniz',
  'Leave it empty for no future inactivation' => 'Gelecekte pasifleştirme olmaması için boş bırakın',
  'The avatars storage directory({path}) does not exists and cannot be created!' => 'Avatar depolama dizini ({path}) mevcut değil ve oluşturulamıyor!',
  'Cannot move the avatar into the correct storage folder!' => 'Avatar doğru depolama klasörüne taşınamıyor!',
  'Please select a past date!' => 'Lütfen geçmiş bir tarih seçin!',
  'Age is {age} but minimum is {min}!' => 'Yaş {age} ancak minimum {min}!',
  'Please select a future date!' => 'Lütfen gelecek bir tarih seçin!',
  'Token' => 'Jeton',
  'Log' => 'Günlük',
  'Category' => 'Kategori',
  'Reference' => 'Referans',
  'Location' => 'Konum',
  'User agent' => 'Kullanıcı aracısı',
  'Remember me' => 'Beni hatırla',
  '2FA code' => '2FA kodu',
  'Invalid login credentials.' => 'Geçersiz giriş bilgileri.',
  'Unable to login with the given identity!' => 'Verilen kimlikle giriş yapılamıyor!',
  'The {className} behavior can only be attach to a Campaign model' => '{className} davranışı yalnızca bir Kampanya modeline eklenebilir',
  'The {className} behavior can only be attach to a Customer model' => '{className} davranışı yalnızca bir Müşteri modeline eklenebilir',
  'Profile info successfully updated!' => 'Profil bilgisi başarıyla güncellendi!',
  'Account info' => 'Hesap bilgisi',
  'Customer info successfully updated!' => 'Müşteri bilgisi başarıyla güncellendi!',
  'Company info successfully updated!' => 'Şirket bilgisi başarıyla güncellendi!',
  'Your account has been successfully disabled!' => 'Hesabınız başarıyla devre dışı bırakıldı!',
  'Disable account' => 'Hesabı devre dışı bırak',
  'Quota usage (count)' => 'Kota kullanımı (sayı)',
  'Quota usage (days)' => 'Kota kullanımı (gün)',
  'Lists' => 'Listeler',
  'Campaigns' => 'Kampanyalar',
  'Subscribers' => 'Aboneler',
  'Delivery servers' => 'Teslimat sunucuları',
  'Bounce servers' => 'Geri dönen e-posta sunucuları',
  'Feedback servers' => 'Geri bildirim sunucuları',
  'Profile' => 'Profil',
  'Export' => 'Dışa Aktar',
  'Please login' => 'Lütfen giriş yapın',
  'This email address is blacklisted!' => 'Bu e-posta adresi kara listeye alınmış!',
  'Congratulations, your account has been created, check your inbox for email confirmation! Please note that sometimes the email might land in spam/junk!' => 'Tebrikler, hesabınız oluşturuldu, e-posta onayı için gelen kutunuzu kontrol edin! Lütfen bazen e-postanın spam/gereksiz klasörüne düşebileceğini unutmayın!',
  'Congratulations, your account has been created, you can login now!' => 'Tebrikler, hesabınız oluşturuldu, şimdi giriş yapabilirsiniz!',
  'Please register' => 'Lütfen kayıt olun',
  'Congratulations, you have successfully confirmed your account.' => 'Tebrikler, hesabınızı başarıyla onayladınız.',
  'You will be able to login once an administrator will approve it.' => 'Bir yönetici onayladıktan sonra giriş yapabileceksiniz.',
  'Congratulations, your account is now ready to use.' => 'Tebrikler, hesabınız şimdi kullanıma hazır.',
  'Please start by filling your account and company info.' => 'Lütfen hesap ve şirket bilgilerinizi doldurarak başlayın.',
  'Retrieve a new password for your account.' => 'Hesabınız için yeni bir şifre alın.',
  'Unable to retrieve all your account data!' => 'Tüm hesap verileriniz alınamıyor!',
  'Your account is not active!' => 'Hesabınız aktif değil!',
  'There is another account using this email address, please fill in the form to recover your password!' => 'Bu e-posta adresini kullanan başka bir hesap var, lütfen şifrenizi kurtarmak için formu doldurun!',
  'Unable to save your account, please contact us if this error persists!' => 'Hesabınız kaydedilemiyor, bu hata devam ederse lütfen bizimle iletişime geçin!',
  'Congratulations, your account has been successfully created.' => 'Tebrikler, hesabınız başarıyla oluşturuldu.',
  'Enter your email address' => 'E-posta adresinizi girin',
  'Invalid email address provided!' => 'Geçersiz e-posta adresi sağlandı!',
  'We\'re sorry, but we don\'t accept registrations from {domain}. <br />Please use another email address, preferably not from a free service!' => 'Üzgünüz, ancak {domain} alan adından kayıt kabul etmiyoruz. <br />Lütfen tercihen ücretsiz bir hizmetten olmayan başka bir e-posta adresi kullanın!',
  'Account usage' => 'Hesap kullanımı',
  'Forgot password?' => 'Şifremi unuttum?',
  'Register' => 'Kayıt ol',
  'Go to login' => 'Girişe git',
  'Company info' => 'Şirket bilgisi',
  'I agree with the specified {terms}' => 'Belirtilen {terms} kabul ediyorum',
  'Please provide your email address where we will send you a confirmation email in order to finish this process.' => 'Bu işlemi tamamlamak için size bir onay e-postası göndereceğimiz e-posta adresinizi lütfen belirtin.',
  'Parent account' => 'Ana hesap',
  'View subaccounts' => 'Alt hesapları görüntüle',
  'Subaccounts' => 'Alt hesaplar',
  'Create new subaccount' => 'Yeni alt hesap oluştur',
  'Permissions' => 'İzinler',
  'Update subaccount' => 'Alt hesabı güncelle',
);
