<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "dashboard" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Dashboard' => 'Kontrol Paneli',
  'Are you sure you want to remove all blacklisted emails?' => 'Tüm kara listeye alınmış e-postaları kaldırmak istediğinizden emin misiniz?',
  'Are you sure you want to remove all login logs?' => 'Tüm giriş kayıtlarını kaldırmak istediğinizden emin misiniz?',
  'Are you sure you want to remove all blacklist monitors?' => 'Tüm kara liste izleyicilerini kaldırmak istediğinizden emin misiniz?',
  'Recent activity' => 'Son etkinlik',
  'Customers' => 'Müşteriler',
  'Campaigns' => 'Kampanyalar',
  'Lists' => 'Listeler',
  'Subscribers' => 'Aboneler',
  'Segments' => 'Segmentler',
  'Delivery servers' => 'Teslimat sunucuları',
  'Templates' => 'Şablonlar',
  'Are you sure you want to remove all suppressed emails?' => 'Tüm bastırılmış e-postaları kaldırmak istediğinizden emin misiniz?',
  'Are you sure you want to remove all suppressed IPs?' => 'Tüm bastırılmış IP\'leri kaldırmak istediğinizden emin misiniz?',
);
