<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "domain_blacklist" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View domains blacklist' => 'Alan adları kara listesini görüntüle',
  'Domains blacklist' => 'Alan adları kara listesi',
  'Domain' => 'Alan adı',
  'Blacklist domains allows you to blacklist emails that belongs to a certain domain/subdomain.' => 'Alan adlarını kara listeye almak, belirli bir alan adı/alt alan adına ait e-postaları kara listeye almanıza olanak tanır.',
  'Import from CSV file' => 'CSV dosyasından içe aktar',
  'If unsure about how to format your file, do an export first and see how the file looks.' => 'Dosyanızın nasıl biçimlendirileceğinden emin değilseniz, önce bir dışa aktarma yapın ve dosyanın nasıl göründüğüne bakın.',
);
