<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "extensions" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View extensions' => 'Eklentileri görüntüle',
  'Extensions' => 'Eklentiler',
  'Your extension has been successfully uploaded!' => 'Eklentiniz başarıyla yüklendi!',
  'Please select an extension archive for upload!' => 'Lütfen yüklemek için bir eklenti arşivi seçin!',
  'The extension "{name}" has been successfully enabled!' => '"{name}" eklentisi başarıyla etkinleştirildi!',
  'The extension "{name}" has been successfully disabled!' => '"{name}" eklentisi başarıyla devre dışı bırakıldı!',
  'The extension "{name}" has been successfully updated!' => '"{name}" eklentisi başarıyla güncellendi!',
  'The extension "{name}" has been successfully deleted!' => '"{name}" eklentisi başarıyla silindi!',
  'The extension "{name}" has failed to update!' => '"{name}" eklentisi güncellenemedi!',
  'Conducting extensions checks for the fresh install...' => 'Yeni kurulum için eklenti kontrolleri yapılıyor...',
  'All extension checks were conducted successfully.' => 'Tüm eklenti kontrolleri başarıyla gerçekleştirildi.',
  'Uploaded extensions' => 'Yüklenen eklentiler',
  'Upload extension' => 'Eklenti yükle',
  'Name' => 'İsim',
  'Description' => 'Açıklama',
  'Version' => 'Sürüm',
  'Author' => 'Yazar',
  'Website' => 'Web sitesi',
  'Extension detail page' => 'Eklenti detay sayfası',
  'Core extensions' => 'Çekirdek eklentiler',
  'Upload extension archive.' => 'Eklenti arşivi yükleyin.',
  'Please note that only zip files are allowed for upload.' => 'Lütfen yükleme için yalnızca zip dosyalarına izin verildiğini unutmayın.',
  'Visit website' => 'Web sitesini ziyaret et',
  'The extension "{name}" needs updating from version {v1} to version {v2}! Please click {here} to run the update!' => '"{name}" eklentisinin {v1} sürümünden {v2} sürümüne güncellenmesi gerekiyor! Güncellemeyi çalıştırmak için lütfen {here} tıklayın!',
  'The extension does not exists.' => 'Eklenti mevcut değil.',
  'The extension is already enabled.' => 'Eklenti zaten etkinleştirilmiş.',
  'The extension {ext} require your application to be at least version {version} but you are currently using version {appVersion}.' => '{ext} eklentisi, uygulamanızın en az {version} sürümünde olmasını gerektiriyor, ancak şu anda {appVersion} sürümünü kullanıyorsunuz.',
  'Enabling the extension {ext} has failed.' => '{ext} eklentisinin etkinleştirilmesi başarısız oldu.',
  'The extension cannot be disabled by configuration.' => 'Eklenti, yapılandırma tarafından devre dışı bırakılamaz.',
  'The extension could not be disabled.' => 'Eklenti devre dışı bırakılamadı.',
  'The extension has to be enabled in order to update it.' => 'Eklentiyi güncellemek için etkinleştirilmesi gerekiyor.',
  'The extension is already at the latest version.' => 'Eklenti zaten en son sürümde.',
  'The extension could not be updated.' => 'Eklenti güncellenemedi.',
  'The extension cannot be deleted by configuration.' => 'Eklenti, yapılandırma tarafından silinemez.',
  'The extension cannot be deleted.' => 'Eklenti silinemez.',
  'Enabled' => 'Etkin',
);
