<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "favorite_pages" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Favorite pages' => 'Favori sayfalar',
  'Are you sure you want to {action} favorites?' => 'Favorileri {action} istediğinizden emin misiniz?',
  'Please click here to {action} favorites' => 'Favorileri {action} için lütfen buraya tıklayın',
  'Page' => 'Sayfa',
  'Customer' => 'Müşteri',
  'User' => 'Kullanıcı',
  'Label' => 'Etiket',
  'Route' => 'Rota',
  'Route params' => 'Rota parametreleri',
  'Route hash' => 'Rota hash değeri',
  'Clicks count' => 'Tıklama sayısı',
  'Reset the clicks counter' => 'Tıklama sayacını sıfırla',
  'The page has been added to favorites successfully' => 'Sayfa başarıyla favorilere eklendi',
  'Are you sure you want to remove this page from favorites?' => 'Bu sayfayı favorilerden kaldırmak istediğinizden emin misiniz?',
  'Please click here to remove this page from favorites' => 'Bu sayfayı favorilerden kaldırmak için lütfen buraya tıklayın',
  'The page has been removed from favorites' => 'Sayfa favorilerden kaldırıldı',
  'Are you sure you want to add this page to favorites?' => 'Bu sayfayı favorilere eklemek istediğinizden emin misiniz?',
  'Please click here to add this page to favorites' => 'Bu sayfayı favorilere eklemek için lütfen buraya tıklayın',
);
