<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "guest_fail_attempt" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View guest fail attempts' => 'Misafir başarısız girişimlerini görüntüle',
  'Guest fail attempts' => 'Misafir başarısız girişimleri',
  'Attempt' => 'Girişim',
  'Ip address' => 'IP adresi',
  'Ip address hash' => 'IP adresi hash değeri',
  'User agent' => 'Kullanıcı tarayıcısı',
  'Place' => 'Yer',
  'Backend login' => 'Yönetici girişi',
);
