<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "ip_blacklist" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'IP address' => 'IP adresi',
  'Customer' => 'Müşteri',
  'Import from CSV file' => 'CSV dosyasından içe aktar',
  'Please note, the csv file must contain a header with at least the ip_address column.' => 'Lütfen unutmayın, csv dosyası en az ip_address sütununu içeren bir başlığa sahip olmalıdır.',
  'Add a new IP to blacklist' => 'Kara listeye yeni bir IP ekle',
  'Please enter a valid IP address!' => 'Lütfen geçerli bir IP adresi girin!',
  'Update blacklisted IP' => 'Kara listedeki IP\'yi güncelle',
);
