<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "ip_location_maxmind" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Status on email open' => 'E-posta açıldığında durum',
  'Status on track url' => 'URL takibinde durum',
  'Status on unsubscribe' => 'Abonelikten çıkıldığında durum',
  'Status on customer login' => 'Müşteri girişinde durum',
  'Sort order' => 'Sıralama düzeni',
  'Whether this service is enabled and can be used' => 'Bu hizmetin etkin olup olmadığı ve kullanılabilirliği',
  'Whether to collect ip location information when a campaign email is opened' => 'Bir kampanya e-postası açıldığında IP konum bilgilerinin toplanıp toplanmayacağı',
  'Whether to collect ip location information when a campaign link is clicked and tracked' => 'Bir kampanya bağlantısı tıklandığında ve takip edildiğinde IP konum bilgilerinin toplanıp toplanmayacağı',
  'Whether to collect ip location information when a subscriber unsubscribes via a campaign' => 'Bir abone, bir kampanya üzerinden abonelikten çıktığında IP konum bilgilerinin toplanıp toplanmayacağı',
  'Whether to collect ip location information when a customer logs in' => 'Bir müşteri giriş yaptığında IP konum bilgilerinin toplanıp toplanmayacağı',
  'If multiple location services active, sort order decides which one queries first' => 'Birden fazla konum hizmeti etkinse, sıralama düzeni hangi sorgunun önce çalışacağını belirler',
  'Ip location service from MaxMind.com' => 'MaxMind.com\'dan IP konum hizmeti',
  'This product includes GeoLite2 data created by MaxMind, available from {from}' => 'Bu ürün, MaxMind tarafından oluşturulan ve {from} adresinden erişilebilen GeoLite2 verilerini içerir',
  'MaxMind.com' => 'MaxMind.com',
  'Offers IP location based on GeoLite2 database created by MaxMind' => 'MaxMind tarafından oluşturulan GeoLite2 veritabanına dayalı IP konum hizmeti sunar',
);
