<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "ip_location" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Ip location services' => 'IP konum hizmetleri',
  'MaxMind.com database' => 'MaxMind.com veritabanı',
  'Name' => 'İsim',
  'Description' => 'Açıklama',
  'Status' => 'Durum',
  'Sort order' => 'Sıralama düzeni',
  'Service detail page' => 'Hizmet detay sayfası',
  'Ip location services are used to collect location data(country, zone, city) when subscribers open the email campaigns or when they click on a trackable url, etc.' => 'IP konum hizmetleri, aboneler e-posta kampanyalarını açtığında veya takip edilebilir bir URL\'ye tıkladığında vb. konum verilerini (ülke, bölge, şehir) toplamak için kullanılır.',
  'This data is then used in campaign reports to show you the exact location where the email campaign has been opened or the location from where the subscriber clicked a link from within the campaign.' => 'Bu veriler daha sonra kampanya raporlarında, e-posta kampanyasının açıldığı tam konumu veya abonenin kampanya içindeki bir bağlantıya tıkladığı konumu göstermek için kullanılır.',
  'Please note, data accuracy will vary between the services. You should test the service website before enable.' => 'Lütfen dikkat edin, veri doğruluğu hizmetler arasında farklılık gösterecektir. Etkinleştirmeden önce hizmet web sitesini test etmelisiniz.',
  'Path on server' => 'Sunucudaki yol',
  'Download' => 'İndir',
  'Action to take' => 'Alınacak eylem',
  'Download and place it in the right path' => 'İndirin ve doğru yola yerleştirin',
  'None' => 'Hiçbiri',
  'This product includes GeoLite2 data created by MaxMind, available from {from}' => 'Bu ürün, MaxMind tarafından oluşturulan ve {from} adresinden erişilebilen GeoLite2 verilerini içerir',
  'Location' => 'Konum',
  'Ip address' => 'IP adresi',
  'Country code' => 'Ülke kodu',
  'Country name' => 'Ülke adı',
  'Zone name' => 'Bölge adı',
  'City name' => 'Şehir adı',
  'Latitude' => 'Enlem',
  'Longitude' => 'Boylam',
  'Timezone' => 'Saat dilimi',
  'The database file which should be located at "{path}" is missing!' => '"{path}" konumunda bulunması gereken veritabanı dosyası eksik!',
  'Please download latest version from {link}, decompress it and place the resulted .mmdb file to be accessible at the above path!' => 'Lütfen en son sürümü {link} adresinden indirin, açın ve oluşan .mmdb dosyasını yukarıdaki yoldan erişilebilir olacak şekilde yerleştirin!',
  'Maxmind\'s site' => 'Maxmind\'in sitesi',
);
