<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "languages" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View available languages' => 'Mevcut dilleri görüntüle',
  'Languages' => 'Diller',
  'Create new language' => 'Yeni dil oluştur',
  'Update language' => 'Dili güncelle',
  'Your language pack has been successfully uploaded!' => 'Dil paketiniz başarıyla yüklendi!',
  'Please select a language pack archive for upload!' => 'Lütfen yüklemek için bir dil paketi arşivi seçin!',
  'Upload language pack' => 'Dil paketi yükle',
  'Please note that only zip files are allowed for upload.' => 'Lütfen yükleme için yalnızca zip dosyalarına izin verildiğini unutmayın.',
  'Language packs contain executable PHP files, please check the packs before upload.' => 'Dil paketleri çalıştırılabilir PHP dosyaları içerir, lütfen yüklemeden önce paketleri kontrol edin.',
  'Language' => 'Dil',
  'Name' => 'İsim',
  'Language code' => 'Dil kodu',
  'Region code' => 'Bölge kodu',
  'Is default language?' => 'Varsayılan dil mi?',
  'The visible language name to distinct between same language but distinct regions (i.e: between English US and English GB)' => 'Aynı dil ancak farklı bölgeler arasında ayırt etmek için görünür dil adı (örn: İngilizce US ve İngilizce GB arasında)',
  '2 letter language code, i.e: en' => '2 harfli dil kodu, örn: tr',
  '2 letter region code, i.e: us. Please do not fill this field unless necessary. For most of the cases, the language code is enough' => '2 harfli bölge kodu, örn: tr. Lütfen gerekli olmadıkça bu alanı doldurmayın. Çoğu durumda dil kodu yeterlidir',
  'Whether this language is the default language for users/customers that have not set a language' => 'Bu dilin, dil ayarı yapmamış kullanıcılar/müşteriler için varsayılan dil olup olmadığı',
  'i.e: English - United States' => 'örn: Türkçe - Türkiye',
  'i.e: en' => 'örn: tr',
  'i.e: us' => 'örn: tr',
  'The archive upload is only allowed for php message source.' => 'Arşiv yüklemesine yalnızca php mesaj kaynağı için izin verilir.',
  'The language directory {dirName} is not valid and was deleted!' => '{dirName} dil dizini geçerli değil ve silindi!',
  'The language "{languageName}" cannot be saved, failure reason: ' => '"{languageName}" dili kaydedilemedi, başarısızlık nedeni: ',
  'Duplicate entry for the language and region code combination!' => 'Dil ve bölge kodu kombinasyonu için yinelenen giriş!',
);
