<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "list_pages" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Pages' => 'Sayfalar',
  'List' => 'Liste',
  'Type' => 'Tür',
  'Content' => 'İçerik',
  'Email subject' => 'E-posta konusu',
  'The following tag is required but was not found in your content: {tag}' => 'Aşağıdaki etiket gereklidir ancak içeriğinizde bulunamadı: {tag}',
  'List pages' => 'Liste sayfaları',
  'Select another list page to edit' => 'Düzenlemek için başka bir liste sayfası seçin',
  'Your unsubscribe form url is:' => 'Abonelikten çıkma formu URL\'niz:',
  'Preview it now!' => 'Şimdi önizleyin!',
  'Your subscribe form url is:' => 'Abone olma formu URL\'niz:',
  'Subscribe form' => 'Abone olma formu',
  'Pending subscribe' => 'Bekleyen abonelik',
  'Subscription confirmed' => 'Abonelik onaylandı',
  'Update Profile' => 'Profili Güncelle',
  'Unsubscribe form' => 'Abonelikten çıkma formu',
  'Unsubscribe confirmation' => 'Abonelikten çıkma onayı',
  'Subscribe confirm email' => 'Abonelik onay e-postası',
  'Unsubscribe confirm email' => 'Abonelikten çıkma onay e-postası',
  'Welcome email' => 'Hoş geldiniz e-postası',
  'Subscription confirmed approval' => 'Abonelik onayı onaylandı',
  'Subscription confirmed approval email' => 'Abonelik onayı onaylama e-postası',
);
