<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "list_page_types" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'List page types' => 'Liste sayfa türleri',
  'Update page type' => 'Sayfa türünü güncelle',
  'Available tags:' => 'Kullanılabilir etiketler:',
  'Type' => 'Tür',
  'Name' => 'İsim',
  'Description' => 'Açıklama',
  'Default content' => 'Varsayılan içerik',
  'Full html' => 'Tam html',
  'Email subject' => 'E-posta konusu',
  'Please note, these pages are the base pages shown in customers area for each list.<br /> The customer has the ability to modify them to fit their needs for any particular list.' => 'Lütfen unutmayın, bu sayfalar her liste için müşteri alanında gösterilen temel sayfalardır.<br /> Müşteri, belirli bir listeye göre ihtiyaçlarına uyacak şekilde bunları değiştirme olanağına sahiptir.',
);
