<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('Doğrudan komut dosyası erişimine izin verilmez');
}

/**
 * "list_import" kategorisi için çeviri dosyası.
 *
 * Bu çeviri, Translate eklentisi tarafından otomatik olarak oluşturulmuştur.
 *
 * @package MailWizz EMA
 * @author MailWizz Geliştirme Ekibi <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Server type' => 'Sunucu türü',
  'Hostname' => 'Ana bilgisayar adı',
  'Port' => 'Bağlantı noktası',
  'Username' => 'Kullanıcı adı',
  'Password' => 'Şifre',
  'Database name' => 'Veritabanı adı',
  'Table name' => 'Tablo adı',
  'Email column' => 'E-posta sütunu',
  'Ignored columns' => 'Yoksayılan sütunlar',
  'i.e: mysql.databaseclusters.com' => 'ör: mysql.databaseclusters.com',
  'i.e: 3306' => 'ör: 3306',
  'i.e: mysqlcluser' => 'ör: mysqlcluser',
  'i.e: superprivatepassword' => 'ör: cokgizlisifre',
  'i.e: my_blog' => 'ör: blogum',
  'i.e: tbl_subscribers' => 'ör: tbl_aboneler',
  'email' => 'e-posta',
  'i.e: id, date_added, status' => 'ör: id, eklenme_tarihi, durum',
  'The server type, if not sure choose mysql' => 'Sunucu türü, emin değilseniz mysql seçin',
  'The hostname of your database server, it can also be the ip address' => 'Veritabanı sunucunuzun ana bilgisayar adı, IP adresi de olabilir',
  'The port where your external database server is listening for connections' => 'Harici veritabanı sunucunuzun bağlantıları dinlediği bağlantı noktası',
  'Your username that unique identifies yourself on the database server' => 'Veritabanı sunucusunda sizi benzersiz şekilde tanımlayan kullanıcı adınız',
  'The password for the username' => 'Kullanıcı adı için şifre',
  'Your database name as you see it in a tool like PhpMyAdmin' => 'PhpMyAdmin gibi bir araçta gördüğünüz veritabanı adınız',
  'Your database table name where your emails are stored, as you see it in a tool like PhpMyAdmin' => 'E-postalarınızın saklandığı veritabanı tablo adınız, PhpMyAdmin gibi bir araçta gördüğünüz gibi',
  'The column that identified the email address' => 'E-posta adresini tanımlayan sütun',
  'Which columns should we ignore and not import. Separate multiple columns by a comma' => 'Hangi sütunları yoksaymalı ve içe aktarmamalıyız. Birden çok sütunu virgülle ayırın',
  'MySQL' => 'MySQL',
  'PostgreSQL' => 'PostgreSQL',
  'SQL Server' => 'SQL Server',
  'Oracle' => 'Oracle',
  'File' => 'Dosya',
  'Unable to create target directory!' => 'Hedef dizin oluşturulamıyor!',
  'Unable to move the uploaded file!' => 'Yüklenen dosya taşınamıyor!',
  'Your uploaded file is not using the UTF-8 charset. Please save it in UTF-8 then upload it again.' => 'Yüklediğiniz dosya UTF-8 karakter setini kullanmıyor. Lütfen UTF-8 olarak kaydedin ve tekrar yükleyin.',
  'Import subscribers into your list' => 'Aboneleri listenize aktarın',
  'Import subscribers' => 'Aboneleri içe aktar',
  'CSV Import' => 'CSV İçe Aktarma',
  'The import file does not exist anymore!' => 'İçe aktarma dosyası artık mevcut değil!',
  'Your file does not contain the header with the fields title!' => 'Dosyanız alan başlıklarını içeren başlığı içermiyor!',
  'Empty column names are not allowed!' => 'Boş sütun adlarına izin verilmez!',
  'Cannot find the "email" column in your file!' => 'Dosyanızda "email" sütunu bulunamıyor!',
  'Your list contains the columns: "{columns}" which are system reserved. Please update your file and change the column names!' => 'Listeniz sistem tarafından ayrılmış olan şu sütunları içeriyor: "{columns}". Lütfen dosyanızı güncelleyin ve sütun adlarını değiştirin!',
  'Found the following column names: {columns}' => 'Şu sütun adları bulundu: {columns}',
  'The import process has finished!' => 'İçe aktarma işlemi tamamlandı!',
  'Your file does not contain enough data to be imported!' => 'Dosyanız içe aktarılacak kadar veri içermiyor!',
  'Checking to see if the tag "{tag}" is defined in your list fields...' => '"{tag}" etiketinin liste alanlarınızda tanımlı olup olmadığı kontrol ediliyor...',
  'The tag "{tag}" is already defined in your list fields.' => '"{tag}" etiketi zaten liste alanlarınızda tanımlı.',
  'The tag "{tag}" is not defined in your list fields, we will try to create it.' => '"{tag}" etiketi liste alanlarınızda tanımlı değil, oluşturmaya çalışacağız.',
  'The tag "{tag}" has been successfully created.' => '"{tag}" etiketi başarıyla oluşturuldu.',
  'The tag "{tag}" cannot be saved, reason: {reason}' => '"{tag}" etiketi kaydedilemiyor, neden: {reason}',
  'Checking the list for the email: "{email}"' => 'Liste şu e-posta için kontrol ediliyor: "{email}"',
  'Failed to save the email "{email}", reason: {reason}' => '"{email}" e-postası kaydedilemedi, neden: {reason}',
  'The email "{email}" was not found, we will try to create it...' => '"{email}" e-postası bulunamadı, oluşturmaya çalışacağız...',
  'Invalid email address!' => 'Geçersiz e-posta adresi!',
  'This email address is blacklisted!' => 'Bu e-posta adresi kara listeye alınmış!',
  'The email "{email}" has been successfully saved.' => '"{email}" e-postası başarıyla kaydedildi.',
  'The email "{email}" has been found, we will update it.' => '"{email}" e-postası bulundu, güncelleyeceğiz.',
  'Imported {count} subscribers starting from row {rowStart} and ending with row {rowEnd}! Going further, please wait...' => '{rowStart} satırından başlayıp {rowEnd} satırıyla biten {count} abone içe aktarıldı! Devam ediliyor, lütfen bekleyin...',
  'Your file cannot be imported, a general error has been encountered: {message}!' => 'Dosyanız içe aktarılamıyor, genel bir hatayla karşılaşıldı: {message}!',
  'Database Import' => 'Veritabanı İçe Aktarma',
  'Cannot find your database columns!' => 'Veritabanı sütunlarınız bulunamıyor!',
  'Cannot find the "email" column in your database!' => 'Veritabanınızda "email" sütunu bulunamıyor!',
  'Your database contains the columns: "{columns}" which are system reserved. Please update your database and change the column names or ignore them!' => 'Veritabanınız sistem tarafından ayrılmış olan şu sütunları içeriyor: "{columns}". Lütfen veritabanınızı güncelleyin ve sütun adlarını değiştirin veya yoksayın!',
  'Your database does not contain enough data to be imported!' => 'Veritabanınız içe aktarılacak kadar veri içermiyor!',
  'Your database cannot be imported, a general error has been encountered: {message}!' => 'Veritabanınız içe aktarılamıyor, genel bir hatayla karşılaşıldı: {message}!',
  'Text Import' => 'Metin İçe Aktarma',
  'Please select a file for import!' => 'Lütfen içe aktarmak için bir dosya seçin!',
  'Unable to queue your import file!' => 'İçe aktarma dosyanız sıraya alınamıyor!',
  'Your file has been queued successfully!' => 'Dosyanız başarıyla sıraya alındı!',
  'From a total of {total} subscribers, so far {totalProcessed} have been processed, {successfullyProcessed} successfully and {errorProcessing} with errors. {percentage} completed.' => 'Toplam {total} aboneden şimdiye kadar {totalProcessed} işlendi, {successfullyProcessed} başarılı ve {errorProcessing} hatalı. %{percentage} tamamlandı.',
  'Import' => 'İçe aktar',
  'Database import progress' => 'Veritabanı içe aktarma ilerlemesi',
  'Back to import options' => 'İçe aktarma seçeneklerine geri dön',
  'The import process is starting, please wait...' => 'İçe aktarma işlemi başlıyor, lütfen bekleyin...',
  'CSV' => 'CSV',
  'Text' => 'Metin',
  'Database' => 'Veritabanı',
  'Url' => 'URL',
  'Import from CSV file' => 'CSV dosyasından içe aktar',
  'Upload file' => 'Dosya yükle',
  'Import from text file' => 'Metin dosyasından içe aktar',
  'Import from external SQL database' => 'Harici SQL veritabanından içe aktar',
  'Please enter your credentials for the external database in order to start the import.' => 'İçe aktarmayı başlatmak için lütfen harici veritabanı için kimlik bilgilerinizi girin.',
  'Connect and import' => 'Bağlan ve içe aktar',
  'Import from url' => 'URL\'den içe aktar',
  'Add a url from where we will import subscribers on a daily basis!' => 'Günlük olarak abone içe aktaracağımız bir URL ekleyin!',
  'Please note that the url has to point to a valid .csv or .txt file' => 'Lütfen URL\'nin geçerli bir .csv veya .txt dosyasına işaret etmesi gerektiğini unutmayın',
  'Save url' => 'URL\'yi kaydet',
  'Ping page' => 'Ping sayfası',
  'This is the PING page, called via iframe when importing files. There is no reason for your to access it.' => 'Bu, dosyaları içe aktarırken iframe aracılığıyla çağrılan PING sayfasıdır. Erişmeniz için bir neden yoktur.',
  'CSV import progress' => 'CSV içe aktarma ilerlemesi',
  'Text file import progress' => 'Metin dosyası içe aktarma ilerlemesi',
  'Please note, we only accept valid CSV files that contain a header, that is the column names for the data to be imported.<br /> We also have a limit on the file size you are allowed to upload, that is {uploadLimit}.<br /> The import process might fail with some of the files, mainly because these are not correctly formatted or they contain invalid data.<br /> You should first do a test import(in a test list) and see if that goes as planned then do it for your actual list.<br /> <strong>Important</strong>: The CSV file column names will be used to create the list TAGS, if a tag does not exist, it will be created.<br /> You can also click <a href="{exampleArchiveHref}" target="_blank">here</a> to see a csv file example.' => 'Lütfen dikkat, yalnızca bir başlık içeren geçerli CSV dosyalarını kabul ediyoruz, yani içe aktarılacak verilerin sütun adları.<br /> Ayrıca yüklemenize izin verilen dosya boyutunda bir sınırımız var, bu {uploadLimit}.<br /> İçe aktarma işlemi bazı dosyalarda başarısız olabilir, bunun başlıca nedeni doğru biçimlendirilmemiş olmaları veya geçersiz veri içermeleridir.<br /> Önce bir test içe aktarması (bir test listesinde) yapmalı ve planlandığı gibi gidip gitmediğini görmeli, ardından gerçek listeniz için yapmalısınız.<br /> <strong>Önemli</strong>: CSV dosyası sütun adları liste ETİKETLERİ oluşturmak için kullanılacaktır, bir etiket mevcut değilse oluşturulacaktır.<br /> Bir csv dosyası örneği görmek için <a href="{exampleArchiveHref}" target="_blank">buraya</a> da tıklayabilirsiniz.',
  'The import process will start shortly. <br /> While the import is running it is recommended you leave this page as it is and wait for the import to finish.<br /> The importer runs in batches of {subscribersPerBatch} subscribers with a pause of {pause} seconds between the batches, therefore the import process might take a while depending on your file size and number of subscribers to import.<br /> Please note, the subscribers number is aproximate if your CSV has empty lines or ends with an empty line or it has duplicate emails(case in which the subscriber will be updated).<br /> This is a tedious process, so sit tight and wait for it to finish.' => 'İçe aktarma işlemi yakında başlayacaktır. <br /> İçe aktarma çalışırken bu sayfayı olduğu gibi bırakmanız ve içe aktarmanın bitmesini beklemeniz önerilir.<br /> İçe aktarıcı, partiler arasında {pause} saniyelik bir duraklamayla {subscribersPerBatch} abonelik partiler halinde çalışır, bu nedenle içe aktarma işlemi dosya boyutunuza ve içe aktarılacak abone sayısına bağlı olarak biraz zaman alabilir.<br /> Lütfen unutmayın, CSV\'nizde boş satırlar varsa veya boş bir satırla bitiyorsa veya yinelenen e-postalar varsa (bu durumda abone güncellenecektir) abone sayısı yaklaşık değerdir.<br /> Bu sıkıcı bir süreçtir, bu yüzden sıkı durun ve bitmesini bekleyin.',
  'From a total of {total} possible subscribers, so far {totalProcessed} have been processed, {successfullyProcessed} successfully and {errorProcessing} with errors. {percentage} completed.' => 'Toplam {total} olası aboneden şimdiye kadar {totalProcessed} işlendi, {successfullyProcessed} başarılı ve {errorProcessing} hatalı. %{percentage} tamamlandı.',
  'Your list already contains {currentFieldsCount} custom fields, the import process cannot create new custom fields({newFieldsCount}), it would go above the list custom fields limit which is currently set to {maxFieldsCount}.' => 'Listeniz zaten {currentFieldsCount} özel alan içeriyor, içe aktarma işlemi yeni özel alanlar ({newFieldsCount}) oluşturamaz, şu anda {maxFieldsCount} olarak ayarlanmış olan liste özel alan sınırının üzerine çıkar.',
  'The import process for list "{listName}" has successfully started, counting {rowsCount} records!' => '"{listName}" listesi için içe aktarma işlemi başarıyla başladı, {rowsCount} kayıt sayılıyor!',
);