<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "list_segments" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Segments' => 'Segmentler',
  'Segment' => 'Segment',
  'List' => 'Liste',
  'Name' => 'İsim',
  'Operator match' => 'Operatör eşleşmesi',
  'Subscribers count' => 'Abone sayısı',
  'Condition' => 'Koşul',
  'Operator' => 'Operatör',
  'Field' => 'Alan',
  'Value' => 'Değer',
  'It will be transformed into an empty value' => 'Boş bir değere dönüştürülecek',
  'It will be transformed into the current date/time in the format of Y-m-d H:i:s (i.e: {datetime})' => 'Y-m-d H:i:s formatında mevcut tarih/saate dönüştürülecek (örn: {datetime})',
  'It will be transformed into the current date in the format of Y-m-d (i.e: {date})' => 'Y-m-d formatında mevcut tarihe dönüştürülecek (örn: {date})',
  'It will rewind the current date by X days and use that as a comparison date' => 'Mevcut tarihi X gün geri saracak ve karşılaştırma tarihi olarak kullanacak',
  'It will forward the current date by X days and use that as a comparison date' => 'Mevcut tarihi X gün ileri alacak ve karşılaştırma tarihi olarak kullanacak',
  'It requires the birthday custom field value to be in the format of Y-m-d (i.e: {date}) in order to work properly' => 'Düzgün çalışması için doğum günü özel alan değerinin Y-m-d formatında olması gerekir (örn: {date})',
  'It will forward the birthday by X days relative to the current date and use that as a comparison date.' => 'Doğum gününü mevcut tarihe göre X gün ileri alacak ve karşılaştırma tarihi olarak kullanacak.',
  'List segments' => 'Liste segmentleri',
  'Your mail list segments' => 'Posta listesi segmentleriniz',
  ' List segments' => ' Liste segmentleri',
  'You are only allowed to add {num} segment conditions.' => 'Yalnızca {num} segment koşulu eklemenize izin verilir.',
  'Current segmentation is too deep and loads too slow, please revise your segment conditions!' => 'Mevcut segmentasyon çok derin ve çok yavaş yükleniyor, lütfen segment koşullarınızı gözden geçirin!',
  'Create a new list segment' => 'Yeni bir liste segmenti oluştur',
  'Update list segment' => 'Liste segmentini güncelle',
  'Your list segment was successfully copied!' => 'Liste segmentiniz başarıyla kopyalandı!',
  'This segment contains {count} subscribers' => 'Bu segment {count} abone içeriyor',
  'Sorry, but there are no subscribers matching your segment.' => 'Üzgünüz, ancak segmentinizle eşleşen abone yok.',
  'Defined conditions:' => 'Tanımlanan koşullar:',
  'Subscribers matching your segment:' => 'Segmentinizle eşleşen aboneler:',
  'Available value tags' => 'Kullanılabilir değer etiketleri',
  'Following tags can be used as dynamic values. They will be replaced as shown below.' => 'Aşağıdaki etiketler dinamik değerler olarak kullanılabilir. Aşağıda gösterildiği gibi değiştirileceklerdir.',
  'Tag' => 'Etiket',
  'Description' => 'Açıklama',
  'any' => 'herhangi biri',
  'all' => 'tümü',
  'Conditions that apply to your list custom fields:' => 'Liste özel alanlarınıza uygulanan koşullar:',
  'Conditions that apply to the campaigns sent to the list this segment belongs to:' => 'Bu segmentin ait olduğu listeye gönderilen kampanyalara uygulanan koşullar:',
  'is' => 'eşittir',
  'is not' => 'eşit değildir',
  'contains' => 'içerir',
  'not contains' => 'içermez',
  'starts with' => 'ile başlar',
  'ends with' => 'ile biter',
  'is greater than' => 'daha büyüktür',
  'is less than' => 'daha küçüktür',
  'not starts with' => 'ile başlamaz',
  'not ends with' => 'ile bitmez',
  'Open' => 'Açma',
  'Click' => 'Tıklama',
  'Day(s)' => 'Gün',
  'Month(s)' => 'Ay',
  'Year(s)' => 'Yıl',
  'Less then or equal' => 'Küçük veya eşit',
  'Less then' => 'Küçük',
  'Greater than or equal' => 'Büyük veya eşit',
  'Greater than' => 'Büyük',
  'Equal' => 'Eşit',
  'Campaign' => 'Kampanya',
  'Campaign action' => 'Kampanya eylemi',
  'Click url' => 'Tıklama URL\'si',
  'Time value' => 'Zaman değeri',
  'Time unit' => 'Zaman birimi',
  'Comparison' => 'Karşılaştırma',
  'Any list campaign' => 'Herhangi bir liste kampanyası',
  'A new segment called "{segmentName}" has been added to the list "{listName}" successfully!' => '"{segmentName}" adlı yeni bir segment, "{listName}" listesine başarıyla eklendi!',
  'The segment called "{segmentName}" belonging to the list "{listName}" has been successfully updated!' => '"{listName}" listesine ait "{segmentName}" adlı segment başarıyla güncellendi!',
  'The segment {segmentName} belonging to the list "{listName}" has been successfully deleted!' => '"{listName}" listesine ait {segmentName} segment başarıyla silindi!',
  'Not Open' => 'Açmama',
  'Not Click' => 'Tıklamama',
  'View archived segments' => 'Arşivlenmiş segmentleri görüntüle',
  'View all list segments' => 'Tüm liste segmentlerini görüntüle',
  'Your list segment was successfully archived!' => 'Liste segmentiniz başarıyla arşivlendi!',
  'Your list segment was successfully unarchived!' => 'Liste segmentiniz başarıyla arşivden çıkarıldı!',
  'Archived segments' => 'Arşivlenmiş segmentler',
  'It will rewind the current date/time by X hours and use that as a comparison' => 'Mevcut tarih/saati X saat geri saracak ve karşılaştırma olarak kullanacak',
  'It will forward the current date/time by X hours and use that as a comparison' => 'Mevcut tarih/saati X saat ileri alacak ve karşılaştırma olarak kullanacak',
  'It will rewind the current date/time by X minutes and use that as a comparison' => 'Mevcut tarih/saati X dakika geri saracak ve karşılaştırma olarak kullanacak',
  'It will forward the current date/time by X minutes and use that as a comparison' => 'Mevcut tarih/saati X dakika ileri alacak ve karşılaştırma olarak kullanacak',
);
