<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('Doğrudan komut dosyası erişimine izin verilmiyor');
}

/**
 * "list_fields" kategorisi için çeviri dosyası.
 *
 * Bu çeviri, Çeviri eklentisi tarafından otomatik olarak oluşturulur.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Custom fields' => 'Özel alanlar',
  'Type' => 'Tür',
  'Name' => 'Ad',
  'Identifier' => 'Tanımlayıcı',
  'Class alias' => 'Sınıf takma adı',
  'Description' => 'Açıklama',
  'Option' => 'Seçenek',
  'Field' => 'Alan',
  'Value' => 'Değer',
  'Is default' => 'Varsayılan mı',
  'The consent text' => 'Onay metni',
  'The consent text shown to the subscriber.' => 'Aboneye gösterilen onay metni.',
  'Value when checked' => 'İşaretlendiğindeki değer',
  'The value of the field when checked.' => 'İşaretlendiğinde alanın değeri.',
  'Maximum stars' => 'Maksimum yıldız',
  'Maximum stars of the rating input' => 'Derecelendirme girdisinin maksimum yıldız sayısı',
  'List' => 'Liste',
  'Label' => 'Etiket',
  'Tag' => 'Etiket',
  'Default value' => 'Varsayılan değer',
  'Help text' => 'Yardım metni',
  'Required' => 'Gerekli',
  'Visibility' => 'Görünürlük',
  'Sort order' => 'Sıralama düzeni',
  'The {attribute} attribute must be unique in the mail list!' => '{attribute} özniteliği posta listesinde benzersiz olmalıdır!',
  '"{tagName}" is reserved!' => '"{tagName}" ayrılmıştır!',
  'This is what your subscribers will see above the input field.' => 'Abonelerinizin giriş alanının üzerinde göreceği budur.',
  'The tag must be unique amoung the list tags. It must start with a letter, end with a letter or number and contain only alpha-numeric chars and underscores, all uppercased. The tag can be used in your templates like: [TAGNAME]' => 'Etiket, liste etiketleri arasında benzersiz olmalıdır. Bir harfle başlamalı, bir harf veya sayıyla bitmeli ve yalnızca alfasayısal karakterler ve alt çizgiler içermelidir, hepsi büyük harfle. Etiket, şablonlarınızda şu şekilde kullanılabilir: [TAGNAME]',
  'In case this field is not required and you need a default value for it. Following tags are recognized: {tags}' => 'Bu alan gerekli değilse ve bunun için varsayılan bir değere ihtiyacınız varsa. Aşağıdaki etiketler tanınır: {tags}',
  'If you need to describe this field to your subscribers.' => 'Bu alanı abonelerinize açıklamanız gerekiyorsa.',
  'Additional description for this field to show to your subscribers.' => 'Abonelerinize göstermek için bu alan için ek açıklama.',
  'Whether this field must be filled in in order to submit the subscription form.' => 'Abonelik formunu göndermek için bu alanın doldurulması gerekip gerekmediği.',
  'Hidden fields are not shown to subscribers.' => 'Gizli alanlar abonelere gösterilmez.',
  'Decide the order of the fields shown in the form.' => 'Formda gösterilen alanların sırasına karar verin.',
  'Subscriber' => 'Abone',
  'Year start' => 'Başlangıç yılı',
  'Year end' => 'Bitiş yılı',
  'Year step' => 'Yıl adımı',
  'Decides with which year to start' => 'Hangi yılla başlayacağına karar verir',
  'Decides with which year to end' => 'Hangi yılla biteceğine karar verir',
  'Decides the number of years it jump each iteration' => 'Her yinelemede kaç yıl atlayacağına karar verir',
  'Add years range field' => 'Yıl aralığı alanı ekle',
  'New years range field' => 'Yeni yıl aralığı alanı',
  'Are you sure you want to remove this field? There is no coming back from this after you save the changes.' => 'Bu alanı kaldırmak istediğinizden emin misiniz? Değişiklikleri kaydettikten sonra bundan geri dönüş yoktur.',
  'Years range field' => 'Yıl aralığı alanı',
  'Add dropdown field' => 'Açılır liste alanı ekle',
  'New dropdown field' => 'Yeni açılır liste alanı',
  'Dropdown options' => 'Açılır liste seçenekleri',
  'Are you sure you want to remove this option? There is no coming back from this after you save the changes.' => 'Bu seçeneği kaldırmak istediğinizden emin misiniz? Değişiklikleri kaydettikten sonra bundan geri dönüş yoktur.',
  'Dropdown field' => 'Açılır liste alanı',
  'Add rating field' => 'Derecelendirme alanı ekle',
  'New rating field' => 'Yeni derecelendirme alanı',
  'Rating field' => 'Derecelendirme alanı',
  'Add checkboxlist field' => 'Onay kutusu listesi alanı ekle',
  'New checkboxlist field' => 'Yeni onay kutusu listesi alanı',
  'Options' => 'Seçenekler',
  'Checkboxlist field' => 'Onay kutusu listesi alanı',
  'In case this field is not required and you need a default value for it. The format must be "Y-m-d H:i:s". Following tags are recognized: {tags}' => 'Bu alan gerekli değilse ve bunun için varsayılan bir değere ihtiyacınız varsa. Biçim "Y-m-d H:i:s" olmalıdır. Aşağıdaki etiketler tanınır: {tags}',
  'Add datetime field' => 'Tarihsaat alanı ekle',
  'New datetime field' => 'Yeni tarihsaat alanı',
  'Datetime field' => 'Tarihsaat alanı',
  'Add geostate field' => 'Coğrafi eyalet alanı ekle',
  'New geostate field' => 'Yeni coğrafi eyalet alanı',
  'Geostate field' => 'Coğrafi eyalet alanı',
  'In case this field is not required and you need a default value for it. The format must be "Y-m-d". Following tags are recognized: {tags}' => 'Bu alan gerekli değilse ve bunun için varsayılan bir değere ihtiyacınız varsa. Biçim "Y-m-d" olmalıdır. Aşağıdaki etiketler tanınır: {tags}',
  'Add date field' => 'Tarih alanı ekle',
  'New date field' => 'Yeni tarih alanı',
  'Date field' => 'Tarih alanı',
  'Add checkbox field' => 'Onay kutusu alanı ekle',
  'New checkbox field' => 'Yeni onay kutusu alanı',
  'Checkbox field' => 'Onay kutusu alanı',
  'Add state field' => 'Eyalet alanı ekle',
  'New state field' => 'Yeni eyalet alanı',
  'State field' => 'Eyalet alanı',
  'Invalid number' => 'Geçersiz numara',
  'Invalid country code' => 'Geçersiz ülke kodu',
  'Too short' => 'Çok kısa',
  'Too long' => 'Çok uzun',
  'Add phone number field' => 'Telefon numarası alanı ekle',
  'New phone number field' => 'Yeni telefon numarası alanı',
  'Phone number field' => 'Telefon numarası alanı',
  'Add url field' => 'URL alanı ekle',
  'New url field' => 'Yeni URL alanı',
  'Url field' => 'URL alanı',
  'Add textarea field' => 'Metin alanı ekle',
  'New textarea field' => 'Yeni metin alanı',
  'Textarea field' => 'Metin alanı',
  'Add consent checkbox' => 'Onay onay kutusu ekle',
  'New consent checkbox' => 'Yeni onay onay kutusu',
  'Consent checkbox' => 'Onay onay kutusu',
  'Add geocity field' => 'Coğrafi şehir alanı ekle',
  'New geocity field' => 'Yeni coğrafi şehir alanı',
  'Geocity field' => 'Coğrafi şehir alanı',
  'Missing the EMAIL tag, this is not acceptable!' => 'EMAIL etiketi eksik, bu kabul edilemez!',
  'This email address is blacklisted!' => 'Bu e-posta adresi kara listeye alınmış!',
  'This email address is already registered in this list!' => 'Bu e-posta adresi bu listede zaten kayıtlı!',
  'Add text field' => 'Metin alanı ekle',
  'New text field' => 'Yeni metin alanı',
  'Text field' => 'Metin alanı',
  'Add geocountry field' => 'Coğrafi ülke alanı ekle',
  'New geocountry field' => 'Yeni coğrafi ülke alanı',
  'Geocountry field' => 'Coğrafi ülke alanı',
  'Add multiselect field' => 'Çoklu seçim alanı ekle',
  'New multiselect field' => 'Yeni çoklu seçim alanı',
  'Multiselect field' => 'Çoklu seçim alanı',
  'Add country field' => 'Ülke alanı ekle',
  'New country field' => 'Yeni ülke alanı',
  'Country field' => 'Ülke alanı',
  'Add radiolist field' => 'Radyo düğmesi listesi alanı ekle',
  'New radiolist field' => 'Yeni radyo düğmesi listesi alanı',
  'Radiolist field' => 'Radyo düğmesi listesi alanı',
  'Add email field' => 'E-posta alanı ekle',
  'New email field' => 'Yeni e-posta alanı',
  'Email field' => 'E-posta alanı',
  'List custom fields' => 'Liste özel alanları',
  'Your mail list does not have any field defined.' => 'Posta listenizde tanımlanmış herhangi bir alan yok.',
  'There is no field type defined yet, please contact the administrator.' => 'Henüz tanımlanmış bir alan türü yok, lütfen yöneticiyle iletişime geçin.',
  'Please note that it will take a while to synchronize the existing subscribers with the new custom fields defaults!' => 'Lütfen mevcut aboneleri yeni özel alan varsayılanlarıyla senkronize etmenin biraz zaman alacağını unutmayın!',
  'Your mail lists custom fields' => 'Posta listelerinizin özel alanları',
  'Hidden fields are rendered in the form but hidden, while None fields are simply not rendered in the form at all.' => 'Gizli alanlar formda oluşturulur ancak gizlenir, None (Hiçbiri) alanları ise formda hiç oluşturulmaz.',
  'Allow A to Z. Case insensitive' => 'A\'dan Z\'ye izin ver. Büyük/küçük harf duyarsız',
  'Allow A to Z and 0 to 9. Case insensitive' => 'A\'dan Z\'ye ve 0\'dan 9\'a izin ver. Büyük/küçük harf duyarsız',
  'Allow A to Z, 0 to 9, dots, spaces, dashes, underscores, new lines, question and exclamation marks. Case insensitive' => 'A\'dan Z\'ye, 0\'dan 9\'a, noktalara, boşluklara, tirelere, alt çizgilere, yeni satırlara, soru ve ünlem işaretlerine izin ver. Büyük/küçük harf duyarsız',
  'Minimum length' => 'Minimum uzunluk',
  'Maximum length' => 'Maksimum uzunluk',
  'Content rule' => 'İçerik kuralı',
  'Content regex' => 'İçerik regex\'i',
  'Minimum length of the text' => 'Metnin minimum uzunluğu',
  'Maximum length of the text' => 'Metnin maksimum uzunluğu',
  'Decides which rule applies to the content. If you need more flexibility, try the regular expressions field' => 'İçeriğe hangi kuralın uygulanacağına karar verir. Daha fazla esnekliğe ihtiyacınız varsa, düzenli ifadeler alanını deneyin',
  'Advanced usage. Filter the content of the field using regular expressions. For example, following case insensitive regex, /^([a-z0-9\\s\\.]+)$/i will only allow letters from A to Z, numbers from 0 to 9, spaces and dots, as many times as needed. Use with care and make sure you test the subscription form afterwards' => 'Gelişmiş kullanım. Alanın içeriğini düzenli ifadeler kullanarak filtreleyin. Örneğin, aşağıdaki büyük/küçük harf duyarsız regex, /^([a-z0-9\\s\\.]+)$/i yalnızca A\'dan Z\'ye harflere, 0\'dan 9\'a sayılara, boşluklara ve noktalara, gerektiği kadar izin verir. Dikkatli kullanın ve ardından abonelik formunu test ettiğinizden emin olun',
  'Default country' => 'Varsayılan ülke',
  'Any scheme' => 'Herhangi bir şema',
  'HTTPS and HTTP' => 'HTTPS ve HTTP',
  'HTTPS only' => 'Yalnızca HTTPS',
  'HTTP only' => 'Yalnızca HTTP',
  'Allowed scheme' => 'İzin verilen şema',
  'Whitelist domains' => 'Beyaz liste alan adları',
  'Blacklist domains' => 'Kara liste alan adları',
  'Allow only domains in this list. Separate multiple domains with a comma. Use only the domain name, i.e: example1.com, example2.com' => 'Yalnızca bu listedeki alan adlarına izin verin. Birden fazla alan adını virgülle ayırın. Yalnızca alan adını kullanın, örn: example1.com, example2.com',
  'Allow all domains except domains in this list. Separate multiple domains with a comma. Use only the domain name, i.e: example1.com, example2.com' => 'Bu listedeki alan adları dışındaki tüm alan adlarına izin verin. Birden fazla alan adını virgülle ayırın. Yalnızca alan adını kullanın, örn: example1.com, example2.com',
  'Your list has {current} custom fields, but you are allowed only {max} custom fields' => 'Listenizde {current} özel alan var, ancak yalnızca {max} özel alana izin veriliyor',
  'You have reached the maximum number of allowed custom fields. Your list has {current} custom fields, but you are allowed only {max} custom fields' => 'İzin verilen maksimum özel alan sayısına ulaştınız. Listenizde {current} özel alan var, ancak yalnızca {max} özel alana izin veriliyor',
  'You have reached the maximum number of allowed custom fields.' => 'İzin verilen maksimum özel alan sayısına ulaştınız.',
  'You have reached the maximum number of allowed custom fields. Your list has {current} custom fields and you are allowed only {max} custom fields.' => 'İzin verilen maksimum özel alan sayısına ulaştınız. Listenizde {current} özel alan var ve yalnızca {max} özel alana izin veriliyor.',
  'Replace at import' => 'İçe aktarmada değiştir',
  'Merge at import' => 'İçe aktarmada birleştir',
  'Importing strategy' => 'İçe aktarma stratejisi',
  'Import values separator' => 'İçe aktarma değerleri ayırıcısı',
  'The default strategy is REPLACE, which means the new subscribers values will replace the old ones. Use MERGE to keep the old ones together with the imported ones.' => 'Varsayılan strateji DEĞİŞTİR\'dir, bu da yeni abone değerlerinin eskilerini değiştireceği anlamına gelir. Eskileri içe aktarılanlarla birlikte tutmak için BİRLEŞTİR\'i kullanın.',
  'This is the glue for the multiple values' => 'Bu, birden çok değer için yapıştırıcıdır',
);
