<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "list_export" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Export subscribers from your list' => 'Listenizdeki aboneleri dışa aktar',
  'Export subscribers' => 'Aboneleri dışa aktar',
  'CSV Export' => 'CSV Dışa Aktarma',
  'Your list has no subscribers to export!' => 'Listenizde dışa aktarılacak abone bulunmuyor!',
  'Cannot create the storage directory for your export!' => 'Dışa aktarmanız için depolama dizini oluşturulamıyor!',
  'Cannot open the storage file for your export!' => 'Dışa aktarmanız için depolama dosyası açılamıyor!',
  'Successfully added the email "{email}" to the export list.' => '"{email}" e-postası dışa aktarma listesine başarıyla eklendi.',
  'Exported {count} subscribers, from {start} to {end}.' => '{start}\'dan {end}\'e kadar {count} abone dışa aktarıldı.',
  'The export is now complete, starting the packing process...' => 'Dışa aktarma şimdi tamamlandı, paketleme işlemi başlıyor...',
  'Packing done, your file will be downloaded now, please wait...' => 'Paketleme tamamlandı, dosyanız şimdi indirilecek, lütfen bekleyin...',
  'Please wait, starting another batch...' => 'Lütfen bekleyin, başka bir toplu işlem başlatılıyor...',
  'The export file has been deleted.' => 'Dışa aktarma dosyası silindi.',
  'Export subscribers from your list segment' => 'Liste segmentinizdeki aboneleri dışa aktarın',
  'Export segment' => 'Segmenti dışa aktar',
  'CSV' => 'CSV',
  'Click to export' => 'Dışa aktarmak için tıklayın',
  'CSV export progress' => 'CSV dışa aktarma ilerlemesi',
  'Back to export options' => 'Dışa aktarma seçeneklerine geri dön',
  'From a total of {total} subscribers, so far {totalProcessed} have been processed, {successfullyProcessed} successfully and {errorProcessing} with errors. {percentage} completed.' => 'Toplam {total} aboneden, şu ana kadar {totalProcessed} tanesi işlendi, {successfullyProcessed} tanesi başarılı ve {errorProcessing} tanesi hatalı. %{percentage} tamamlandı.',
  'The export process is starting, please wait...' => 'Dışa aktarma işlemi başlıyor, lütfen bekleyin...',
  'Export' => 'Dışa Aktar',
);
