<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "mailer" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'A very fast mailer.' => 'Çok hızlı bir e-posta gönderici.',
  'System testing mailer, only simulate sending.' => 'Sistem test e-posta göndericisi, sadece gönderimi simüle eder.',
  'A fully compliant mailer.' => 'Tam uyumlu bir e-posta gönderici.',
  'Next generation mailer.' => 'Yeni nesil e-posta gönderici.',
);
