<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "messages" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View messages' => 'Mesajları görüntüle',
  'Messages' => 'Mesajlar',
  'Create new message' => 'Yeni mesaj oluştur',
  'Update message' => 'Mesajı güncelle',
  'View message' => 'Mesajı görüntüle',
  'All messages were marked as seen!' => 'Tüm mesajlar görüldü olarak işaretlendi!',
  'You have {n} unread messages!' => '{n} okunmamış mesajınız var!',
  'See all messages' => 'Tüm mesajları gör',
  'Message' => 'Mesaj',
  'User' => 'Kullanıcı',
  'Title' => 'Başlık',
  'Unseen' => 'Görülmemiş',
  'Seen' => 'Görülmüş',
  'Customer' => 'Müşteri',
  'here' => 'burada',
  'Email "{email}" has requested to be blocked! You can see more details {here}!' => 'E-posta "{email}" engellenmek istedi! Daha fazla ayrıntıyı {here} görebilirsiniz!',
  'A new abuse report has been created for the campaign "{campaign_name}". Please visit the "<a href="{abuse_reports_url}">Abuse Reports</a>" area to handle it!' => '"{campaign_name}" kampanyası için yeni bir kötüye kullanım raporu oluşturuldu. Lütfen işlem yapmak için "<a href="{abuse_reports_url}">Kötüye Kullanım Raporları</a>" alanını ziyaret edin!',
  'Sync list custom fields' => 'Liste özel alanlarını senkronize et',
  'Completed the sync custom fields process for the "{list}" list' => '"{list}" listesi için özel alanları senkronize etme işlemi tamamlandı',
  'Started the sync custom fields process for the "{list}" list' => '"{list}" listesi için özel alanları senkronize etme işlemi başlatıldı',
  'A subscriber has been rejected from joining the {list} list because the system was not able to find a suitable delivery server to send the email' => 'Sistem e-postayı göndermek için uygun bir gönderim sunucusu bulamadığından, bir abone {list} listesine katılmaktan reddedildi',
  'Nice message to customer' => 'Müşteriye güzel mesaj',
  'Very long and important message that should be read immediately.' => 'Hemen okunması gereken çok uzun ve önemli mesaj.',
);
