<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "misc" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View campaigns delivery logs' => 'Kampanya gönderim günlüklerini görüntüle',
  'Campaigns delivery logs' => 'Kampanya gönderim günlükleri',
  'View campaigns bounce logs' => 'Kampanya geri dönüş günlüklerini görüntüle',
  'Campaigns bounce logs' => 'Kampanya geri dönüş günlükleri',
  'View campaigns stats' => 'Kampanya istatistiklerini görüntüle',
  'View delivery servers usage logs' => 'Gönderim sunucuları kullanım günlüklerini görüntüle',
  'Delivery servers usage logs' => 'Gönderim sunucuları kullanım günlükleri',
  'Delivery temporary errors were successfully deleted!' => 'Gönderim geçici hataları başarıyla silindi!',
  'View PHP info' => 'PHP bilgisini görüntüle',
  'PHP info' => 'PHP bilgisi',
  'View archived logs' => 'Arşivlenmiş günlükleri görüntüle',
  'View current logs' => 'Güncel günlükleri görüntüle',
  'Delete delivery temporary errors' => 'Gönderim geçici hatalarını sil',
  'Are you sure you want to delete the delivery temporary errors? Please note that this will affect running campaigns, continue only if you really know what you are doing!' => 'Gönderim geçici hatalarını silmek istediğinizden emin misiniz? Lütfen bunun çalışan kampanyaları etkileyeceğini unutmayın, yalnızca ne yaptığınızı gerçekten biliyorsanız devam edin!',
);
