<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "notes" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View notes for {name}' => '{name} için notları görüntüle',
  'Notes' => 'Notlar',
  'Note' => 'Not',
  'Created by' => 'Oluşturan',
  'Customer' => 'Müşteri',
  'Title' => 'Başlık',
  'View notes' => 'Notları görüntüle',
  'Create new note' => 'Yeni not oluştur',
  'Your note contents. Please keep in mind that it will be encrypted' => 'Not içeriğiniz. Lütfen şifrelenecek olduğunu unutmayın',
  'Update note' => 'Notu güncelle',
  'Create new note for {name}' => '{name} için yeni not oluştur',
  'Update note for {name}' => '{name} için notu güncelle',
);
