<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "orders" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View orders' => 'Siparişleri görüntüle',
  'Orders' => 'Siparişler',
  'Create order' => 'Sipariş oluştur',
  'Update order' => 'Siparişi güncelle',
  'View your order' => 'Siparişinizi görüntüleyin',
  'Invoice' => 'Fatura',
  'Subtotal' => 'Ara toplam',
  'Tax' => 'Vergi',
  'Discount' => 'İndirim',
  'Total' => 'Toplam',
  'Total due' => 'Ödenecek toplam',
  'Paid' => 'Ödendi',
  'Extra notes' => 'Ek notlar',
  'Please try again later!' => 'Lütfen daha sonra tekrar deneyin!',
  'Unable to create the invoices storage directory!' => 'Fatura depolama dizini oluşturulamıyor!',
  'Unable to create the invoice!' => 'Fatura oluşturulamıyor!',
  'Your requested invoice - {ref}' => 'Talep ettiğiniz fatura - {ref}',
  'The invoice has been successfully emailed!' => 'Fatura başarıyla e-postalandı!',
  'Unable to email the invoice!' => 'Fatura e-postayla gönderilemiyor!',
  'This order applies for the "{planName}" pricing plan.' => 'Bu sipariş "{planName}" fiyatlandırma planı için geçerlidir.',
  'Notes' => 'Notlar',
  'Transaction info' => 'İşlem bilgisi',
  'Amount' => 'Tutar',
  'Status' => 'Durum',
  'Email invoice' => 'Faturayı e-posta ile gönder',
  'View invoice' => 'Faturayı görüntüle',
  'Update this order' => 'Bu siparişi güncelle',
  'Back to orders' => 'Siparişlere geri dön',
  'View order' => 'Siparişi görüntüle',
  'Please note that any order added/changed from this area is not verified nor it goes through a payment gateway.' => 'Lütfen bu alandan eklenen/değiştirilen hiçbir siparişin doğrulanmadığını ve bir ödeme geçidi üzerinden geçmediğini unutmayın.',
  'Updating orders from this area is useful for offline orders mostly or for payment corrections.' => 'Bu alandan siparişleri güncellemek çoğunlukla çevrimdışı siparişler veya ödeme düzeltmeleri için kullanışlıdır.',
  'If the order is incomplete, pending or due and changed to complete, the customer will be affected and the price plan will be assigned properly.' => 'Sipariş tamamlanmamış, beklemede veya vadesi gelmiş ise ve tamamlandı olarak değiştirilirse, müşteri etkilenecek ve fiyat planı uygun şekilde atanacaktır.',
  'Reference' => 'Referans',
  'Billing date' => 'Fatura tarihi',
  'Due date' => 'Son ödeme tarihi',
  'Plan' => 'Plan',
  'Quantity' => 'Miktar',
  'Price' => 'Fiyat',
  'Page' => 'Sayfa',
  'of' => '/',
  'Order' => 'Sipariş',
  'Order no.' => 'Sipariş no.',
  'Customer' => 'Müşteri',
  'Promo code' => 'Promosyon kodu',
  'Currency' => 'Para birimi',
  'Tax percent' => 'Vergi yüzdesi',
  'Tax value' => 'Vergi değeri',
  'The customer this order applies to, autocomplete enabled' => 'Bu siparişin uygulandığı müşteri, otomatik tamamlama etkin',
  'The price plan included in this order, autocomplete enabled' => 'Bu siparişe dahil edilen fiyat planı, otomatik tamamlama etkin',
  'The promo code applied to this order, autocomplete enabled' => 'Bu siparişe uygulanan promosyon kodu, otomatik tamamlama etkin',
  'Customer, autocomplete enabled' => 'Müşteri, otomatik tamamlama etkin',
  'Plan, autocomplete enabled' => 'Plan, otomatik tamamlama etkin',
  'Promo code, autocomplete enabled' => 'Promosyon kodu, otomatik tamamlama etkin',
  'VAT Number: {vat_number}' => 'KDV Numarası: {vat_number}',
  'Transaction' => 'İşlem',
  'Transaction uid' => 'İşlem kimliği',
  'Payment gateway name' => 'Ödeme geçidi adı',
  'Payment gateway transaction' => 'Ödeme geçidi işlemi',
  'Payment gateway response' => 'Ödeme geçidi cevabı',
  'Note' => 'Not',
  'If you have particular notes about this order, please type them here...' => 'Bu sipariş hakkında özel notlarınız varsa, lütfen buraya yazın...',
  'Admin' => 'Yönetici',
  'By {author} at ' => '{author} tarafından ',
  'View your orders' => 'Siparişlerinizi görüntüleyin',
  'A new order has been placed!' => 'Yeni bir sipariş verildi!',
  'Your order details!' => 'Sipariş ayrıntılarınız!',
  'Payment method' => 'Ödeme yöntemi',
  'Enter your promo code here' => 'Promosyon kodunuzu buraya girin',
  'Amount due' => 'Ödenecek tutar',
  'Payment from' => 'Ödeme yapan',
  'Payment to' => 'Ödeme yapılan',
  'Unit price' => 'Birim fiyat',
);
