<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "pages" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View pages' => 'Sayfaları görüntüle',
  'Pages' => 'Sayfalar',
  'Create new page' => 'Yeni sayfa oluştur',
  'Update page' => 'Sayfayı güncelle',
  'Page' => 'Sayfa',
  'Title' => 'Başlık',
  'Slug' => 'Slug',
  'Content' => 'İçerik',
  'My page title' => 'Sayfa başlığım',
  'my-page-title' => 'sayfa-basligim',
  'This page is inactive, only site admins can see it!' => 'Bu sayfa etkin değil, yalnızca site yöneticileri görebilir!',
  'Active' => 'Etkin',
);
