<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "payment_gateway_stripe_subscriptions" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Stripe subscriptions' => 'Stripe abonelikleri',
  'Retrieve payments using stripe subscriptions' => 'Stripe aboneliklerini kullanarak ödemeleri al',
  'Stripe subscriptions payment gateway' => 'Stripe abonelikleri ödeme geçidi',
  'Please do not forget to add the webhook url into your Stripe dashboard, this is maybe the most important thing you have to do, without it, customers will not be assigned to customer groups.' => 'Lütfen webhook URL\'sini Stripe kontrol panelinize eklemeyi unutmayın, bu belki de yapmanız gereken en önemli şeydir, bu olmadan müşteriler müşteri gruplarına atanmayacaktır.',
  'The webhook url that you have to add is: {url}' => 'Eklemeniz gereken webhook URL\'si: {url}',
  'Please note that {here} you have a screenshot showing how the webhook has to be added and what event type you must select.' => 'Lütfen {here} webhook\'un nasıl ekleneceğini ve hangi etkinlik türünü seçmeniz gerektiğini gösteren bir ekran görüntüsüne sahip olduğunuzu unutmayın.',
  'Subscriptions are created on a monthly basis, so please make sure your customer groups sending quota targets the monthly time unit, this is very important.' => 'Abonelikler aylık olarak oluşturulur, bu nedenle lütfen müşteri gruplarınızın gönderim kotasının aylık zaman birimini hedeflediğinden emin olun, bu çok önemlidir.',
  'test' => 'test',
  'live' => 'canlı',
  'Test secret key' => 'Test gizli anahtarı',
  'Test publishable key' => 'Test yayınlanabilir anahtarı',
  'Live secret key' => 'Canlı gizli anahtarı',
  'Live publishable key' => 'Canlı yayınlanabilir anahtarı',
  'Expiration move to group' => 'Sona erdiğinde gruba taşı',
  'Mode' => 'Mod',
  'Whether to move the customer in this group when the subscription ends' => 'Abonelik sona erdiğinde müşteriyi bu gruba taşıyıp taşımamak',
  'Whether the payments are live or run in test mode' => 'Ödemelerin canlı mı yoksa test modunda mı çalıştığı',
  'Whether this gateway is enabled and can be used for payments processing' => 'Bu geçidin etkinleştirilip etkinleştirilmediği ve ödeme işlemleri için kullanılıp kullanılamayacağı',
  'The sort order for this gateway' => 'Bu geçit için sıralama düzeni',
  'Subscriptions' => 'Abonelikler',
);
