<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "payment_gateway_mollie" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Mollie' => 'Mollie',
  'Retrieve payments using mollie' => 'Mollie kullanarak ödemeleri al',
  'Mollie payment gateway' => 'Mollie ödeme geçidi',
  'Credit card number' => 'Kredi kartı numarası',
  'Exp. month' => 'Son kullanma ayı',
  'Exp. year' => 'Son kullanma yılı',
  'Cvv' => 'CVV',
);
