<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "payment_gateways" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Payment gateways' => 'Ödeme geçitleri',
  'Name' => 'İsim',
  'Description' => 'Açıklama',
  'Status' => 'Durum',
  'Sort order' => 'Sıralama düzeni',
  'Gateway detail page' => 'Geçit detay sayfası',
  'The payment gateways are implemented as extensions, you\'ll want to enable them from the extensions area first and then manage them from here.' => 'Ödeme geçitleri uzantılar olarak uygulanmıştır, önce bunları uzantılar alanından etkinleştirmek ve ardından buradan yönetmek isteyeceksiniz.',
);
