<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "payment_gateway_authorize_net" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'AuthorizeNet payment gateway' => 'AuthorizeNet ödeme geçidi',
  'Api login ID' => 'API giriş kimliği',
  'Transaction key' => 'İşlem anahtarı',
  'Mode' => 'Mod',
  'Whether the payments are live or run in sandbox mode' => 'Ödemelerin canlı mı yoksa sandbox modunda mı çalıştığı',
  'Whether this gateway is enabled and can be used for payments processing' => 'Bu geçidin etkinleştirilip etkinleştirilmediği ve ödeme işlemleri için kullanılıp kullanılamayacağı',
  'The sort order for this gateway' => 'Bu geçit için sıralama düzeni',
  'AuthorizeNet' => 'AuthorizeNet',
  'Retrieve payments using authorize net' => 'AuthorizeNet kullanarak ödemeleri al',
  'Credit card number' => 'Kredi kartı numarası',
  'Exp. month' => 'Son kullanma ayı',
  'Exp. year' => 'Son kullanma yılı',
);
