<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "payment_gateway_stripe" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Stripe payment gateway' => 'Stripe ödeme geçidi',
  'Test secret key' => 'Test gizli anahtarı',
  'Test publishable key' => 'Test yayınlanabilir anahtarı',
  'Live secret key' => 'Canlı gizli anahtarı',
  'Live publishable key' => 'Canlı yayınlanabilir anahtarı',
  'Mode' => 'Mod',
  'Whether the payments are live or run in test mode' => 'Ödemelerin canlı mı yoksa test modunda mı çalıştığı',
  'Whether this gateway is enabled and can be used for payments processing' => 'Bu geçidin etkinleştirilip etkinleştirilmediği ve ödeme işlemleri için kullanılıp kullanılamayacağı',
  'The sort order for this gateway' => 'Bu geçit için sıralama düzeni',
  'Stripe' => 'Stripe',
  'Retrieve payments using stripe' => 'Stripe kullanarak ödemeleri al',
  'Credit card number' => 'Kredi kartı numarası',
  'Exp. month' => 'Son kullanma ayı',
  'Exp. year' => 'Son kullanma yılı',
  'Cvv' => 'CVV',
  'Your credit card number seems invalid!' => 'Kredi kartı numaranız geçersiz görünüyor!',
  'Invalid date!' => 'Geçersiz tarih!',
  'Invalid CVV!' => 'Geçersiz CVV!',
  'All your data is sent over a secure connection without touching our server.' => 'Tüm verileriniz, sunucumuza dokunmadan güvenli bir bağlantı üzerinden gönderilir.',
  'test' => 'test',
  'live' => 'canlı',
);
