<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "payment_gateway_paypal" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Your order is in "{status}" status, it usually takes a few minutes to be processed and if everything is fine, your pricing plan will become active!' => 'Siparişiniz "{status}" durumunda, işlenmesi genellikle birkaç dakika sürer ve her şey yolunda giderse fiyatlandırma planınız aktif olacak!',
  'Paypal' => 'PayPal',
  'Retrieve payments using paypal' => 'PayPal kullanarak ödemeleri al',
  'Paypal payment gateway' => 'PayPal ödeme geçidi',
  'Email' => 'E-posta',
  'Mode' => 'Mod',
  'Your paypal email address where the payments should go' => 'Ödemelerin gönderileceği PayPal e-posta adresiniz',
  'Whether the payments are live or run in sandbox' => 'Ödemelerin canlı mı yoksa sandbox\'da mı çalıştığı',
  'Whether this gateway is enabled and can be used for payments processing' => 'Bu geçidin etkinleştirilip etkinleştirilmediği ve ödeme işlemleri için kullanılıp kullanılamayacağı',
  'The sort order for this gateway' => 'Bu geçit için sıralama düzeni',
  'You will be redirected to pay securely on paypal.com official website!' => 'Güvenli bir şekilde ödeme yapmak için paypal.com resmi web sitesine yönlendirileceksiniz!',
  'sandbox' => 'sandbox',
  'live' => 'canlı',
);
