<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "payment_gateway_razorpay" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Razorpay' => 'Razorpay',
  'Retrieve payments using razorpay.com' => 'Razorpay.com kullanarak ödemeleri al',
  'Razorpay payment gateway' => 'Razorpay ödeme geçidi',
  'Razorpay payments' => 'Razorpay ödemeleri',
  'Api key' => 'API anahtarı',
  'Api secret' => 'API gizli anahtarı',
  'One of your api keys as defined in your razorpay dashboard' => 'Razorpay kontrol panelinizde tanımlanmış API anahtarlarınızdan biri',
  'The api secret for the selected api key' => 'Seçilen API anahtarı için API gizli anahtarı',
  'Whether this gateway is enabled and can be used for payments processing' => 'Bu geçidin etkinleştirilip etkinleştirilmediği ve ödeme işlemleri için kullanılıp kullanılamayacağı',
  'The sort order for this gateway' => 'Bu geçit için sıralama düzeni',
  'Razorpay - www.razorpay.com' => 'Razorpay - www.razorpay.com',
);
