<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "payment_gateway_offline" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Offline payment' => 'Çevrimdışı ödeme',
  'Your order is in "{status}" status, once it gets approved, your pricing plan will become active!' => 'Siparişiniz "{status}" durumunda, onaylandığında fiyatlandırma planınız aktif olacak!',
  'Offline' => 'Çevrimdışı',
  'Retrieve payments offline' => 'Ödemeleri çevrimdışı olarak al',
  'Offline payment gateway' => 'Çevrimdışı ödeme geçidi',
  'Offline payments' => 'Çevrimdışı ödemeler',
  'Description' => 'Açıklama',
  'The needed details for customers to see and to use in order to make the offline payment' => 'Müşterilerin çevrimdışı ödeme yapabilmesi için görmesi ve kullanması gereken ayrıntılar',
  'Whether this gateway is enabled and can be used for payments processing' => 'Bu geçidin etkinleştirilip etkinleştirilmediği ve ödeme işlemleri için kullanılıp kullanılamayacağı',
  'The sort order for this gateway' => 'Bu geçit için sıralama düzeni',
);
