<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "payment_gateway_twocheckout" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  '2Checkout' => '2Checkout',
  'Retrieve payments using 2Checkout' => '2Checkout kullanarak ödemeleri al',
  '2Checkout payment gateway' => '2Checkout ödeme geçidi',
  'Publishable key' => 'Yayınlanabilir anahtar',
  'Private key' => 'Özel anahtar',
  'Seller ID / Account number' => 'Satıcı ID / Hesap numarası',
  'Mode' => 'Mod',
  'Whether the payments are live or run in sandbox mode' => 'Ödemelerin canlı mı yoksa sandbox modunda mı çalıştığı',
  'Whether this gateway is enabled and can be used for payments processing' => 'Bu geçidin etkinleştirilip etkinleştirilmediği ve ödeme işlemleri için kullanılıp kullanılamayacağı',
  'The sort order for this gateway' => 'Bu geçit için sıralama düzeni',
  'Credit card number' => 'Kredi kartı numarası',
  'Exp. month' => 'Son kullanma ayı',
  'Exp. year' => 'Son kullanma yılı',
  'Cvv' => 'CVV',
  'Please wait, processing your request, this might take a while...' => 'Lütfen bekleyin, isteğiniz işleniyor, bu biraz zaman alabilir...',
  'All your data is sent over a secure connection without touching our server.' => 'Tüm verileriniz, sunucumuza dokunmadan güvenli bir bağlantı üzerinden gönderilir.',
  'Please go to your {account} and fill in your company info before checking out.' => 'Lütfen ödeme yapmadan önce {account} adresinize gidin ve şirket bilgilerinizi doldurun.',
  'account' => 'hesap',
);
