<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "price_plans" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View price plans' => 'Fiyat planlarını görüntüle',
  'Price plans' => 'Fiyat planları',
  'Create new price plan' => 'Yeni fiyat planı oluştur',
  'Update price plan' => 'Fiyat planını güncelle',
  'Your price plan has been successfully copied!' => 'Fiyat planınız başarıyla kopyalandı!',
  'Unable to copy the price plan!' => 'Fiyat planı kopyalanamıyor!',
  'Plan' => 'Plan',
  'Plan uid' => 'Plan kimliği',
  'Customer group' => 'Müşteri grubu',
  'Name' => 'İsim',
  'Price' => 'Fiyat',
  'Description' => 'Açıklama',
  'Recommended' => 'Önerilen',
  'Visible' => 'Görünür',
  'The group where the customer will be moved after purchasing this plan. Make sure the group has proper permissions and limits' => 'Müşterinin bu planı satın aldıktan sonra taşınacağı grup. Grubun uygun izinlere ve sınırlara sahip olduğundan emin olun',
  'The price plan name, used in customer display area, orders, etc' => 'Müşteri görüntüleme alanında, siparişlerde vb. kullanılan fiyat planı adı',
  'The amount the customers will be charged when buying this plan' => 'Müşterilerin bu planı satın alırken ödeyecekleri tutar',
  'A detailed description about the price plan features' => 'Fiyat planı özellikleri hakkında ayrıntılı bir açıklama',
  'Whether this plan has the recommended badge on it' => 'Bu planın üzerinde önerilen rozeti olup olmadığı',
  'Whether this plan is visible in customers area' => 'Bu planın müşteri alanında görünür olup olmadığı',
  'Price plan' => 'Fiyat planı',
  'Submit payment' => 'Ödeme gönder',
  'Place offline order' => 'Çevrimdışı sipariş ver',
  'Unable to load the payment gateway!' => 'Ödeme geçidi yüklenemiyor!',
  'Invalid payment gateway setup!' => 'Geçersiz ödeme geçidi kurulumu!',
  'The specified price plan is invalid!' => 'Belirtilen fiyat planı geçersiz!',
  'Selected price plan allows {n} {w} but you already have {m}, therefore you cannot apply for the plan!' => 'Seçilen fiyat planı {n} {w} izin veriyor ancak zaten {m} var, bu nedenle plana başvuramazsınız!',
  'Unable to set a correct currency!' => 'Doğru para birimi ayarlanamıyor!',
  'Price plans payment' => 'Fiyat planları ödemesi',
  'Unable to load payment data!' => 'Ödeme verileri yüklenemiyor!',
  'Invalid currency specified!' => 'Geçersiz para birimi belirtildi!',
  'Cannot save your order!' => 'Siparişiniz kaydedilemiyor!',
  'The provided promotional code does not exists anymore!' => 'Sağlanan promosyon kodu artık mevcut değil!',
  'This promo code requires that select a price plan that costs at least {amount}!' => 'Bu promosyon kodu, en az {amount} maliyeti olan bir fiyat planı seçmenizi gerektirir!',
  'You have reached the maximum usage times for this promo code!' => 'Bu promosyon kodu için maksimum kullanım süresine ulaştınız!',
  'This promo code has reached the maximum usage times!' => 'Bu promosyon kodu maksimum kullanım süresine ulaştı!',
  'The promo code has been successfully applied!' => 'Promosyon kodu başarıyla uygulandı!',
  'You have selected the "{planName}" pricing plan.' => '"{planName}" fiyatlandırma planını seçtiniz.',
  'Apply code' => 'Kodu uygula',
  'Available price plans' => 'Mevcut fiyat planları',
  'Select payment method' => 'Ödeme yöntemini seçin',
  'Payment gateway selection' => 'Ödeme geçidi seçimi',
  'Proceed to payment' => 'Ödemeye geç',
  'Congratulations, you have successfully purchased the price plan!' => 'Tebrikler, fiyat planını başarıyla satın aldınız!',
  'The payment id is missing.' => 'Ödeme kimliği eksik.',
  'Something went wrong!' => 'Bir şeyler yanlış gitti!',
  'The payment could not be retrieved.' => 'Ödeme alınamadı.',
  'Subscription created in Mollie. Waiting for the webhook with the payment to activate it' => 'Mollie\'de abonelik oluşturuldu. Etkinleştirmek için ödeme ile webhook bekleniyor',
  'The Mollie subscription is not active. Since the payment is made you should check your Mollie account.' => 'Mollie aboneliği aktif değil. Ödeme yapıldığından Mollie hesabınızı kontrol etmelisiniz.',
  'The order id could not be retrieved from the Mollie payment meta.' => 'Sipariş kimliği Mollie ödeme meta verisinden alınamadı.',
  'The customer id could not be retrieved from the Mollie payment meta.' => 'Müşteri kimliği Mollie ödeme meta verisinden alınamadı.',
  'Please note that plan activation can take a few minutes!' => 'Plan aktivasyonunun birkaç dakika sürebileceğini lütfen unutmayın!',
  'Your payment has been declined!' => 'Ödemeniz reddedildi!',
  'Place order' => 'Sipariş ver',
  'The order could not be retrieved.' => 'Sipariş alınamadı.',
  'The customer could not be retrieved.' => 'Müşteri alınamadı.',
);
