<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "promo_codes" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View promo codes' => 'Promosyon kodlarını görüntüle',
  'Promo codes' => 'Promosyon kodları',
  'Create new promo code' => 'Yeni promosyon kodu oluştur',
  'Update promo code' => 'Promosyon kodunu güncelle',
  'Code' => 'Kod',
  'Type' => 'Tür',
  'Discount' => 'İndirim',
  'Total amount' => 'Toplam tutar',
  'Total usage' => 'Toplam kullanım',
  'Customer usage' => 'Müşteri kullanımı',
  'Date start' => 'Başlangıç tarihi',
  'Date end' => 'Bitiş tarihi',
  'The promotional code' => 'Promosyon kodu',
  'The type of the promotional code' => 'Promosyon kodunun türü',
  'The discount received after applying this promotional code' => 'Bu promosyon kodu uygulandıktan sonra alınan indirim',
  'The amount of the price plan in order for this promotional code to apply' => 'Bu promosyon kodunun uygulanması için fiyat planının tutarı',
  'The maximum number of usages for this promotional code. Set it to 0 for unlimited' => 'Bu promosyon kodu için maksimum kullanım sayısı. Sınırsız için 0 olarak ayarlayın',
  'How many times a customer can use this promotional code. Set it to 0 for unlimited' => 'Bir müşterinin bu promosyon kodunu kaç kez kullanabileceği. Sınırsız için 0 olarak ayarlayın',
  'The start date for this promotional code' => 'Bu promosyon kodu için başlangıç tarihi',
  'The end date for this promotional code' => 'Bu promosyon kodu için bitiş tarihi',
  'i.e: FREE100' => 'örn: FREE100',
  'i.e: 10' => 'örn: 10',
  'i.e: 30' => 'örn: 30',
  'i.e: 1' => 'örn: 1',
  'i.e: {date}' => 'örn: {date}',
  'fixed amount' => 'sabit tutar',
  'percentage' => 'yüzde',
  'i.e: 2021-11-05' => 'örn: 2021-11-05',
  'i.e: 2021-12-05' => 'örn: 2021-12-05',
  'i.e: 2021-11-26' => 'örn: 2021-11-26',
  'i.e: 2021-12-26' => 'örn: 2021-12-26',
  'i.e: 2021-11-27' => 'örn: 2021-11-27',
  'i.e: 2021-12-27' => 'örn: 2021-12-27',
  'i.e: 2021-11-29' => 'örn: 2021-11-29',
  'i.e: 2021-12-29' => 'örn: 2021-12-29',
  'i.e: 2023-11-17' => 'örn: 2023-11-17',
  'i.e: 2023-12-17' => 'örn: 2023-12-17',
  'i.e: 2024-08-26' => 'örn: 2024-08-26',
  'i.e: 2024-09-25' => 'örn: 2024-09-25',
  'i.e: 2024-08-27' => 'örn: 2024-08-27',
  'i.e: 2024-09-26' => 'örn: 2024-09-26',
);
