<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('Doğrudan komut dosyası erişimine izin verilmez');
}

/**
 * "survey_fields" kategorisi için çeviri dosyası.
 *
 * Bu çeviri, Translate eklentisi tarafından otomatik olarak oluşturulmuştur.
 *
 * @package MailWizz EMA
 * @author MailWizz Geliştirme Ekibi <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Custom fields' => 'Özel alanlar',
  'Minimum value' => 'Minimum değer',
  'Maximum value' => 'Maksimum değer',
  'Step size' => 'Adım boyutu',
  'Value type' => 'Değer türü',
  'Minimum value of the number input' => 'Sayı girişinin minimum değeri',
  'Maximum value of the number input' => 'Sayı girişinin maksimum değeri',
  'Step size of the number input' => 'Sayı girişinin adım boyutu',
  'Integer and float' => 'Tamsayı ve ondalık sayı',
  'Integer only' => 'Yalnızca tamsayı',
  'Minimum length' => 'Minimum uzunluk',
  'Maximum length' => 'Maksimum uzunluk',
  'Minimum length of the text' => 'Metnin minimum uzunluğu',
  'Maximum length of the text' => 'Metnin maksimum uzunluğu',
  'The consent text' => 'Onay metni',
  'The consent text shown to the responder.' => 'Katılımcıya gösterilen onay metni.',
  'Value when checked' => 'İşaretlendiğindeki değer',
  'The value of the field when checked.' => 'İşaretlendiğinde alanın değeri.',
  'Option' => 'Seçenek',
  'Field' => 'Alan',
  'Name' => 'Ad',
  'Value' => 'Değer',
  'Is default' => 'Varsayılan mı',
  'Type' => 'Tür',
  'List' => 'Liste',
  'Label' => 'Etiket',
  'Default value' => 'Varsayılan değer',
  'Help text' => 'Yardım metni',
  'Description' => 'Açıklama',
  'Required' => 'Gerekli',
  'Visibility' => 'Görünürlük',
  'Sort order' => 'Sıralama düzeni',
  'This is what your responders will see above the input field.' => 'Katılımcılarınızın giriş alanının üzerinde göreceği şey budur.',
  'In case this field is not required and you need a default value for it.' => 'Bu alan gerekli değilse ve bunun için varsayılan bir değere ihtiyacınız varsa.',
  'If you need to describe this field to your responders.' => 'Bu alanı katılımcılarınıza açıklamanız gerekiyorsa.',
  'Additional description for this field to show to your responders.' => 'Katılımcılarınıza göstermek için bu alana ek açıklama.',
  'Whether this field must be filled in in order to submit the subscription form.' => 'Abonelik formunu göndermek için bu alanın doldurulması gerekip gerekmediği.',
  'Hidden fields are not shown to responders.' => 'Gizli alanlar katılımcılara gösterilmez.',
  'Decide the order of the fields shown in the form.' => 'Formda gösterilen alanların sırasına karar verin.',
  'Identifier' => 'Tanımlayıcı',
  'Class alias' => 'Sınıf takma adı',
  'Maximum stars' => 'Maksimum yıldız',
  'Maximum stars of the rating input' => 'Derecelendirme girişinin maksimum yıldızı',
  'Responder' => 'Katılımcı',
  'Year start' => 'Başlangıç yılı',
  'Year end' => 'Bitiş yılı',
  'Year step' => 'Yıl adımı',
  'Decides with which year to start' => 'Hangi yılla başlayacağına karar verir',
  'Decides with which year to end' => 'Hangi yılla biteceğine karar verir',
  'Decides the number of years it jump each iteration' => 'Her yinelemede kaç yıl atlayacağına karar verir',
  'Add years range field' => 'Yıl aralığı alanı ekle',
  'Years range field' => 'Yıl aralığı alanı',
  'Are you sure you want to remove this field? There is no coming back from this after you save the changes.' => 'Bu alanı kaldırmak istediğinizden emin misiniz? Değişiklikleri kaydettikten sonra geri dönüşü yoktur.',
  'Add dropdown field' => 'Açılır liste alanı ekle',
  'New dropdown field' => 'Yeni açılır liste alanı',
  'Dropdown options' => 'Açılır liste seçenekleri',
  'Are you sure you want to remove this option? There is no coming back from this after you save the changes.' => 'Bu seçeneği kaldırmak istediğinizden emin misiniz? Değişiklikleri kaydettikten sonra geri dönüşü yoktur.',
  'Dropdown field' => 'Açılır liste alanı',
  'Add rating field' => 'Derecelendirme alanı ekle',
  'New rating field' => 'Yeni derecelendirme alanı',
  'Rating field' => 'Derecelendirme alanı',
  'Add checkboxlist field' => 'Onay kutusu listesi alanı ekle',
  'New checkboxlist field' => 'Yeni onay kutusu listesi alanı',
  'Options' => 'Seçenekler',
  'Checkboxlist field' => 'Onay kutusu listesi alanı',
  'In case this field is not required and you need a default value for it. The format must be "Y-m-d H:i:s".' => 'Bu alan gerekli değilse ve bunun için varsayılan bir değere ihtiyacınız varsa. Biçim "Y-m-d H:i:s" olmalıdır.',
  'Add datetime field' => 'Tarih saat alanı ekle',
  'New datetime field' => 'Yeni tarih saat alanı',
  'Datetime field' => 'Tarih saat alanı',
  'Add geostate field' => 'Coğrafi eyalet alanı ekle',
  'New geostate field' => 'Yeni coğrafi eyalet alanı',
  'Geostate field' => 'Coğrafi eyalet alanı',
  'In case this field is not required and you need a default value for it. The format must be "Y-m-d".' => 'Bu alan gerekli değilse ve bunun için varsayılan bir değere ihtiyacınız varsa. Biçim "Y-m-d" olmalıdır.',
  'Add date field' => 'Tarih alanı ekle',
  'New date field' => 'Yeni tarih alanı',
  'Date field' => 'Tarih alanı',
  'Add checkbox field' => 'Onay kutusu alanı ekle',
  'New checkbox field' => 'Yeni onay kutusu alanı',
  'Checkbox field' => 'Onay kutusu alanı',
  'Add state field' => 'Eyalet alanı ekle',
  'New state field' => 'Yeni eyalet alanı',
  'State field' => 'Eyalet alanı',
  'Invalid number' => 'Geçersiz numara',
  'Invalid country code' => 'Geçersiz ülke kodu',
  'Too short' => 'Çok kısa',
  'Too long' => 'Çok uzun',
  'Add phone number field' => 'Telefon numarası alanı ekle',
  'New phone number field' => 'Yeni telefon numarası alanı',
  'Phone number field' => 'Telefon numarası alanı',
  'Add url field' => 'URL alanı ekle',
  'New url field' => 'Yeni URL alanı',
  'Url field' => 'URL alanı',
  'Add number field' => 'Sayı alanı ekle',
  'New number field' => 'Yeni sayı alanı',
  'Number field' => 'Sayı alanı',
  'Add textarea field' => 'Metin alanı ekle',
  'New textarea field' => 'Yeni metin alanı',
  'Textarea field' => 'Metin alanı',
  'Add consent checkbox' => 'Onay onay kutusu ekle',
  'New consent checkbox' => 'Yeni onay onay kutusu',
  'Consent checkbox' => 'Onay onay kutusu',
  'Add geocity field' => 'Coğrafi şehir alanı ekle',
  'New geocity field' => 'Yeni coğrafi şehir alanı',
  'Geocity field' => 'Coğrafi şehir alanı',
  'Add text field' => 'Metin alanı ekle',
  'New text field' => 'Yeni metin alanı',
  'Text field' => 'Metin alanı',
  'Add geocountry field' => 'Coğrafi ülke alanı ekle',
  'New geocountry field' => 'Yeni coğrafi ülke alanı',
  'Geocountry field' => 'Coğrafi ülke alanı',
  'Add multiselect field' => 'Çoklu seçim alanı ekle',
  'New multiselect field' => 'Yeni çoklu seçim alanı',
  'Multiselect field' => 'Çoklu seçim alanı',
  'Add country field' => 'Ülke alanı ekle',
  'New country field' => 'Yeni ülke alanı',
  'Country field' => 'Ülke alanı',
  'Add radiolist field' => 'Radyo düğmesi listesi alanı ekle',
  'New radiolist field' => 'Yeni radyo düğmesi listesi alanı',
  'Radiolist field' => 'Radyo düğmesi listesi alanı',
  'Add email field' => 'E-posta alanı ekle',
  'New email field' => 'Yeni e-posta alanı',
  'Email field' => 'E-posta alanı',
  'There is no field type defined yet, please contact the administrator.' => 'Henüz tanımlanmış bir alan türü yok, lütfen yöneticiyle iletişime geçin.',
  'Your survey fields' => 'Anket alanlarınız',
  'Survey fields' => 'Anket alanları',
  'Fields' => 'Alanlar',
  'Your survey does not have any field defined.' => 'Anketinizde tanımlanmış herhangi bir alan yok.',
  'Hidden fields are rendered in the form but hidden, while None fields are simply not rendered in the form at all.' => 'Gizli alanlar formda oluşturulur ancak gizlenir, None alanları ise formda hiç oluşturulmaz.',
  'New years range field' => 'Yeni yıl aralığı alanı',
);