<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "survey_segments" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Segments' => 'Segmentler',
  'Segment' => 'Segment',
  'Survey' => 'Anket',
  'Name' => 'Ad',
  'Operator match' => 'Operatör eşleşmesi',
  'Responders count' => 'Yanıtlayan sayısı',
  'Condition' => 'Koşul',
  'Operator' => 'Operatör',
  'Field' => 'Alan',
  'Value' => 'Değer',
  'It will be transformed into an empty value' => 'Boş bir değere dönüştürülecektir',
  'It will be transformed into the current date/time in the format of Y-m-d H:i:s (i.e: {datetime})' => 'Y-m-d H:i:s biçiminde geçerli tarih/saate dönüştürülecektir (örn: {datetime})',
  'It will be transformed into the current date in the format of Y-m-d (i.e: {date})' => 'Y-m-d biçiminde geçerli tarihe dönüştürülecektir (örn: {date})',
  'Your mail survey segments' => 'Posta anket segmentleriniz',
  'Survey segments' => 'Anket segmentleri',
  ' Survey segments' => ' Anket segmentleri',
  'You are only allowed to add {num} segment conditions.' => 'Yalnızca {num} segment koşulu eklemenize izin verilir.',
  'Current segmentation is too deep and loads too slow, please revise your segment conditions!' => 'Mevcut segmentasyon çok derin ve çok yavaş yükleniyor, lütfen segment koşullarınızı gözden geçirin!',
  'Your survey segments' => 'Anket segmentleriniz',
  'Create a new survey segment' => 'Yeni bir anket segmenti oluştur',
  'Update survey segment' => 'Anket segmentini güncelle',
  'Your survey segment was successfully copied!' => 'Anket segmentiniz başarıyla kopyalandı!',
  'This segment contains {count} responders' => 'Bu segment {count} yanıtlayıcı içeriyor',
  'Sorry, but there are no responders matching your segment.' => 'Üzgünüz, ancak segmentinizle eşleşen yanıtlayıcı yok.',
  'Defined conditions:' => 'Tanımlanan koşullar:',
  'Responders matching your segment:' => 'Segmentinizle eşleşen yanıtlayıcılar:',
  'Available value tags' => 'Kullanılabilir değer etiketleri',
  'Following tags can be used as dynamic values. They will be replaced as shown below.' => 'Aşağıdaki etiketler dinamik değerler olarak kullanılabilir. Aşağıda gösterildiği gibi değiştirileceklerdir.',
  'Tag' => 'Etiket',
  'Description' => 'Açıklama',
);
