<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('No direct script access allowed');
}

/**
 * Translation file for "taxes" category.
 *
 * This translation is automatically generated by the Translate extension.
 *
 * @package MailWizz EMA
 * @author MailWizz Development Team <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'View taxes' => 'Vergileri görüntüle',
  'Taxes' => 'Vergiler',
  'Create new tax' => 'Yeni vergi oluştur',
  'Update tax' => 'Vergiyi güncelle',
  'Tax' => 'Vergi',
  'Country' => 'Ülke',
  'Zone' => 'Bölge',
  'Name' => 'Ad',
  'Percent' => 'Yüzde',
  'Is global' => 'Genel mi',
  'The country for which this tax applies' => 'Bu verginin geçerli olduğu ülke',
  'The zone/state for which this tax applies' => 'Bu verginin geçerli olduğu bölge/eyalet',
  'The name of this tax' => 'Bu verginin adı',
  'How much from the total amount of the order this max means, use a number' => 'Bu maksimumun siparişin toplam tutarından ne kadar anlamına geldiği, bir sayı kullanın',
  'Whether this tax is global, i.e: applies for customers that don\'t match other taxes' => 'Bu verginin genel olup olmadığı, yani: diğer vergilerle eşleşmeyen müşteriler için geçerli olup olmadığı',
);
