<?php declare(strict_types=1);
if (!defined('MW_PATH')) {
    exit('Doğrudan komut dosyası erişimine izin verilmez');
}

/**
 * "users" kategorisi için çeviri dosyası.
 *
 * Bu çeviri, Translate eklentisi tarafından otomatik olarak oluşturulmuştur.
 *
 * @package MailWizz EMA
 * @author MailWizz Geliştirme Ekibi <support@mailwizz.com>
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
return array (
  'Remember me' => 'Beni hatırla',
  '2FA code' => '2FA kodu',
  'Invalid login credentials.' => 'Geçersiz giriş bilgileri.',
  'Unable to login with the given identity!' => 'Verilen kimlikle giriş yapılamıyor!',
  'View users' => 'Kullanıcıları görüntüle',
  'Users' => 'Kullanıcılar',
  'Create new user' => 'Yeni kullanıcı oluştur',
  'You are not allowed to update the master administrator!' => 'Ana yöneticiyi güncelleme yetkiniz yok!',
  'Update user' => 'Kullanıcıyı güncelle',
  'Update account' => 'Hesabı güncelle',
  'User info successfully updated!' => 'Kullanıcı bilgileri başarıyla güncellendi!',
  '2FA' => '2FA',
  'Please login' => 'Lütfen giriş yapın',
  'Retrieve a new password for your account.' => 'Hesabınız için yeni bir şifre alın.',
  'Update user group' => 'Kullanıcı grubunu güncelle',
  'Use any authenticator app such as Google Authenticator to scan the QR code below.' => 'Aşağıdaki QR kodunu taramak için Google Authenticator gibi herhangi bir kimlik doğrulama uygulamasını kullanın.',
  'You will then use the authenticator app to generate the code to login in the app.' => 'Daha sonra uygulamaya giriş yapmak için kodu oluşturmak üzere kimlik doğrulama uygulamasını kullanacaksınız.',
  'Sign in to start your session' => 'Oturumunuzu başlatmak için giriş yapın',
  'Forgot password?' => 'Şifrenizi mi unuttunuz?',
  'Go to login' => 'Girişe git',
  'Enter the code generated by the authenticator app' => 'Kimlik doğrulama uygulaması tarafından oluşturulan kodu girin',
  'Update your account data.' => 'Hesap verilerinizi güncelleyin.',
  'User' => 'Kullanıcı',
  'Language' => 'Dil',
  'Group' => 'Grup',
  'First name' => 'Ad',
  'Last name' => 'Soyad',
  'Email' => 'E-posta',
  'Password' => 'Şifre',
  'Timezone' => 'Zaman dilimi',
  'Avatar' => 'Avatar',
  'New avatar' => 'Yeni avatar',
  'Removable' => 'Kaldırılabilir',
  'Confirm email' => 'E-postayı onayla',
  'Confirm password' => 'Şifreyi onayla',
  '2FA enabled' => '2FA etkinleştirildi',
  'Please make sure you scan the QR code in your authenticator application before enabling this feature, otherwise you will be locked out from your account' => 'Lütfen bu özelliği etkinleştirmeden önce QR kodunu kimlik doğrulama uygulamanızda taradığınızdan emin olun, aksi takdirde hesabınız kilitlenecektir',
  'The avatars storage directory({path}) does not exists and cannot be created!' => 'Avatar depolama dizini ({path}) mevcut değil ve oluşturulamıyor!',
  'Cannot move the avatar into the correct storage folder!' => 'Avatar doğru depolama klasörüne taşınamıyor!',
  'Request' => 'İstek',
  'Reset key' => 'Sıfırlama anahtarı',
  'Ip address' => 'IP adresi',
  'Token' => 'Belirteç',
  'You are impersonating the customer {customerName}.' => '{customerName} müşterisinin kimliğine bürünüyorsunuz.',
  'Please click {linkBack} to logout in order to finish impersonating.' => 'Kimliğe bürünmeyi bitirmek için lütfen çıkış yapmak üzere {linkBack} bağlantısına tıklayın.',
);